import type { Progression, ResearchPath } from "../../../server/src/sim/progression";
export type Vec2 = { x: number; y: number };
export type TerritoryStateName = "safe" | "contested" | "infested" | "overrun" | "reclaiming";
export type WarSectorState = "secure" | "contested" | "infested" | "overrun" | "reclaiming";
export type OperationStatus = "staging" | "active" | "survived" | "failed" | "evacuated";
export type RoadClass = "interstate_highway" | "state_highway" | "county_road" | "local_road" | "service_road";
export type RoadRenderClass = "highway" | "secondary" | "dirt";
export type RoadPurpose = "connect_city" | "connect_town" | "farm_access" | "industrial_access" | "gas_station_access" | "hospital_access" | "military_checkpoint" | "survivor_outpost" | "zombie_source" | "residential_grid" | "rural_connector" | "service_spur" | "deployment_access";
export type RoadEndpointKind = "major_city" | "town" | "sector_center" | "bridge" | "port" | "deployment_lot" | "infestation_site" | "checkpoint" | "road_intersection" | "highway_exit" | "poi";
export type TownKind = "town" | "city" | "checkpoint" | "gas_station" | "radio_tower" | "bridge";
export type InfestationKind = "hive" | "hospital" | "mall" | "tunnel" | "graveyard" | "factory";
export type TowerType = "rifle" | "cannon" | "flame" | "shock" | "floodlight" | "squadBeacon";
export type EquipmentType = "airstrike" | "barbedWire" | "overclockBooster" | "proximityMine" | "fieldRepairKit" | "roadFlare";
export type EquipmentStack = { type: EquipmentType; count: number };
export type LootSatchel = { id: string; ownerPlayerId: string; contractId: string; x: number; y: number; itemType: EquipmentType; quantity: number; droppedAt: number };
export type PlacedEquipment = { id: string; ownerPlayerId: string; contractId: string; type: "airstrike" | "barbedWire" | "proximityMine" | "roadFlare"; x: number; y: number; placedAt: number; expiresAt: number };
export type UtilityStructureType = "squad_beacon";
export type SquadSlotStatus = "empty" | "ai_joined" | "player_joined" | "locked";
export type SquadRole = "builder" | "repair" | "gunner" | "scavenger" | "signal";
export type BaseSquadSlot = { id: string; baseId: string; status: SquadSlotStatus; commanderId?: string; commanderName?: string; isAI: boolean; role?: SquadRole; joinedAt?: number };
export type SquadCommander = { id: string; name: string; isAI: boolean; role: SquadRole; baseId: string; contribution: number; status: "joining" | "active" | "downed" | "left"; joinedAt: number };
export type Territory = { id: string; name: string; x: number; y: number; w: number; h: number; polygon?: Vec2[]; labelPoint?: Vec2; state: TerritoryStateName; threatLevel: number; infestation: number; pressure: number; neighbors: string[] };
export type RoadNodeDefinition = { id: string; x: number; y: number; kind: "hub" | "junction" | "landmark" | "infestation" };
export type RoadSegment = { id: string; territoryId: string; points: Vec2[]; nodeIds?: string[]; width: number; kind?: RoadRenderClass; roadClass?: RoadClass; purpose?: RoadPurpose; label?: string; showLabel?: boolean; lotEligible?: boolean };
export type TownDefinition = { id: string; name: string; x: number; y: number; territoryId: string; kind: TownKind };
export type InfestationPointDefinition = { id: string; name: string; x: number; y: number; territoryId: string; nodeId: string; kind: InfestationKind };
export type BuildPad = { id: string; x: number; y: number; radius: number; kind: "tower" | "utility" | "trap"; contractId?: string; distanceToRoute?: number; routeIndex?: number; occupiedBy?: string };
export type RoadsideLot = { id: string; territoryId: string; roadSegmentId: string; x: number; y: number; worldX?: number; worldY?: number; w: number; h: number; side: "left" | "right"; status: "empty" | "reserved" | "occupied" | "blocked" | "overrun"; ownerPlayerId?: string; nearbyRoadPoint: Vec2; entrancePoint: Vec2; drivewayPoints?: Vec2[]; pads: BuildPad[] };
export type StrategicDeploymentContext = { planetId: "colony" | "earth" | "planet2-missouri"; regionId: string; regionName: string; centerLat: number; centerLon: number; worldX?: number; worldY?: number; roadAccessLat?: number; roadAccessLon?: number; roadId?: string; roadName?: string; threatLevel: number; infestation: number; state: TerritoryStateName };
export type PlayerState = Progression & { id: string; name: string; scrap: number; fuel: number; signal: number; baseId?: string; activeOperationId?: string; protectedUntil: number; redeployCooldownUntil: number; equipmentStash?: EquipmentStack[]; equipmentBar?: EquipmentType[] };
export type BaseState = { id: string; ownerPlayerId: string; ownerName: string; isAI: boolean; territoryId: string; lotId: string; operationId?: string; coreX: number; coreY: number; worldX?: number; worldY?: number; anchorX?: number; anchorY?: number; entryX?: number; entryY?: number; insertedAt?: number; lastMovedAt?: number; driveSpeed?: number; hp: number; maxHp: number; shieldEndsAt: number; status: "setup" | "active" | "underAttack" | "packed" | "destroyed"; heading?: number; kind: "command" | "reclaim"; joinable?: boolean; squadBeaconLevel?: number; squadSlots?: BaseSquadSlot[] };
export type TowerState = { pathTiers?: Partial<Record<ResearchPath, number>>; id: string; ownerPlayerId: string; baseId: string; padId: string; type: TowerType; x: number; y: number; level: number; range: number; damage: number; fireRate: number; lastFiredAt: number; shotX?: number; shotY?: number; packed?: boolean; boostWaveIndex?: number };
export type ZombieState = { id: string; contractId: string; territoryId: string; type: "walker" | "shambler" | "crawler" | "runner" | "stalker" | "bloater" | "armored" | "skitter" | "ravager" | "brute" | "zombieKing"; x: number; y: number; hp: number; maxHp: number; speed: number; routeIndex: number; alive: boolean; reachedCore: boolean; routeId?: string; spawnpointId?: string; roadFollowing?: boolean; burningUntil?: number; burnDamagePerSecond?: number; burnOwnerPlayerId?: string };
export type SpawnSourceKind = "overrun_road" | "infested_town" | "hospital_ruin" | "factory_ruin" | "tunnel" | "highway_exit" | "graveyard" | "zombie_hive" | "collapsed_bridge";
export type ZombieSpawnpoint = { id: string; contractId: string; name: string; kind: SpawnSourceKind; worldX: number; worldY: number; roadId: string; threatLevel: number; distanceToBase: number };
export type HordeRoute = { id: string; contractId: string; spawnpointId: string; roadIds: string[]; points: Vec2[]; routeDanger: number; routeLength: number; finalApproachPoint: Vec2 };
export type ContractSpawnOrder = { spawnpointId: string; routeId: string; zombieType: ZombieState["type"]; roadFollowing: boolean };
export type WavePlan = { contractId: string; waveIndex: number; spawnGroups: Array<{ spawnpointId: string; routeId: string; zombieType: ZombieState["type"]; count: number; spacingMs: number }> };
export type DefenseContract = { deployedAt?: number;
  id: string; ownerPlayerId: string; baseId: string; sectorId: string; territoryId: string; lotId: string;
  basePosition: Vec2; corePosition: Vec2; spawnpoints: ZombieSpawnpoint[]; routes: HordeRoute[]; buildPads: BuildPad[];
  nextWaveAt: number; nextSpawnAt: number; waveIndex: number; difficulty: number; threatLevel: number; routeDanger: number;
  status: "setup" | "active" | "paused" | "survived" | "failed" | "evacuated"; queue: ContractSpawnOrder[]; activeRouteIds: string[]; currentWavePlan?: WavePlan;
  spawnPointId?: string; routePoints?: Vec2[];
};
export type WorldStatic = { worldWidth: number; worldHeight: number; territories: Territory[]; roads: RoadSegment[]; outline?: Vec2[]; roadNodes?: RoadNodeDefinition[]; towns?: TownDefinition[]; infestations?: InfestationPointDefinition[] };
export type WarSector = { id: string; name: string; regionId?: string; centerLat?: number; centerLon?: number; centerX?: number; centerY?: number; state: WarSectorState; threatLevel: number; pressure: number; infestation: number; supply: number; activeOperationIds: string[]; aiOperationCount: number; playerOperationCount: number; recommended: boolean; isFrontline: boolean; lastEventText?: string };
export type WarOperation = { id: string; sectorId: string; ownerPlayerId: string; ownerName: string; isAI: boolean; kind: "defense" | "reclaim"; status: OperationStatus; startedAt: number; updatedAt: number; lotId?: string; baseId?: string; contribution: number; wavesSurvived: number; pressureReduced: number; casualties: number; visibleMarkerX?: number; visibleMarkerY?: number; visibleLat?: number; visibleLon?: number; sharedBaseSlots: number; squadFilledSlots?: number; joinable: boolean; squadBeaconBuilt: boolean };
export type Snapshot = { worldDeaths?: Array<{id:string;x:number;y:number;at:number}>; serverTime: number; localPlayerId?: string; players: PlayerState[]; territories: Territory[]; lots: RoadsideLot[]; bases: BaseState[]; towers: TowerState[]; zombies: ZombieState[]; contracts: DefenseContract[]; warSectors: WarSector[]; warOperations: WarOperation[]; squadCommanders: SquadCommander[]; activityFeed: string[]; radio: string; lootSatchels?: LootSatchel[]; placedEquipment?: PlacedEquipment[] };
