import assert from 'node:assert/strict';import {createRequire} from 'node:module';import fs from 'node:fs';
const require=createRequire(import.meta.url),{chromium}=require('C:/Users/Swagg/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('output',{recursive:true});
const browser=await chromium.launch({headless:true,channel:'msedge'});
try{
 const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(process.env.REWARDS_URL??'http://127.0.0.1:5243');await p.waitForFunction(()=>window.__FORGE_DEV__?.scene.isActive('Menu'));
 const audit=await p.evaluate(async()=>{
 const {COSMETICS,sanitizeOutfit,outfitTexture}=await import('/src/assets/cosmetics.ts');const {LOOT_POOL}=await import('/src/game/lootCatalog.ts');const {lootChance}=await import('/src/game/economy.ts');const s=window.__FORGE_DEV__.scene.getScene('Menu');
 let frames=0;for(const c of COSMETICS.character){const key=outfitTexture(s,sanitizeOutfit({character:c.id}));for(let f=0;f<12;f++){if(!s.textures.getFrame(key,f))throw Error('Missing frame '+key+f);frames++;}}
 for(const a of ['puppy','cat','rat','cerberus','kangaroo'])for(const h of ['party','fedora','unicorn'])for(const retro of [false,true]){const key=outfitTexture(s,sanitizeOutfit({character:a,animalHat:h,retroCostumes:retro?[a]:[]}));for(let f=0;f<12;f++){if(!s.textures.getFrame(key,f))throw Error('Missing hat frame');frames++;}}
 if(LOOT_POOL.find(i=>i.id==='aria').rarity!==4)throw Error('Aria rarity');if(LOOT_POOL.some((x,i)=>i&&x.rarity<LOOT_POOL[i-1].rarity))throw Error('Unsorted pool');
 const odds=LOOT_POOL.reduce((n,x)=>n+lootChance(x,LOOT_POOL),0);if(Math.abs(odds-100)>1e-6)throw Error('Invalid odds');
 localStorage.setItem('jump-royale-wallet-v1',JSON.stringify({gold:100,owned:[],rewards:[],spinPoints:0,freeSpins:10}));
 return {frames,odds,characters:COSMETICS.character.length};});console.log(audit);
 for(const name of ['Daily missions','Party and profile','Leaderboards','Wallpapers','Open settings']){await p.getByRole('button',{name,exact:true}).click();assert.equal(await p.locator('dialog[open]').count(),1,name);await p.mouse.click(5,5);assert.equal(await p.locator('dialog[open]').count(),0,name+' outside');}
 await p.getByRole('button',{name:'Open wardrobe',exact:true}).click();await p.getByRole('tab',{name:'Character',exact:true}).click();
 assert(await p.evaluate(async()=>{const {itemRarity}=await import('/src/game/lootCatalog.ts');const r=[...document.querySelectorAll('.equipment-card')].map(x=>itemRarity('character',x.dataset.piece));return r.every((n,i)=>!i||n>=r[i-1]);}));
 await p.keyboard.press('Escape');assert(await p.locator('.wardrobe-overlay').isHidden());assert.equal(await p.locator('dialog[open]').count(),0);
 await p.keyboard.press('Escape');assert(await p.locator('.game-settings').isVisible());await p.keyboard.press('Escape');assert.equal(await p.locator('dialog[open]').count(),0);
 await p.getByRole('button',{name:/Open loot box/}).click();await p.locator('.loot-gold-add').click();assert.equal(await p.locator('dialog[open]').count(),2);await p.keyboard.press('Escape');assert(await p.locator('#loot-dialog').isVisible());assert.equal(await p.locator('dialog[open]').count(),1);
 await p.locator('.loot-help-toggle').click();await p.keyboard.press('Escape');assert(await p.locator('#loot-free-help').isHidden());assert(await p.locator('#loot-dialog').isVisible());
 async function spin(slot,id,duplicate=false,closeDuring=false){await p.evaluate(async({slot,id,duplicate})=>{const {LOOT_POOL}=await import('/src/game/lootCatalog.ts');const item=LOOT_POOL.find(x=>x.slot===slot&&x.id===id),tier=LOOT_POOL.filter(x=>x.rarity===item.rarity),w=JSON.parse(localStorage.getItem('jump-royale-wallet-v1'));w.owned=duplicate?tier.map(x=>x.slot+':'+x.id):[];w.gold=100;w.freeSpins=10;localStorage.setItem('jump-royale-wallet-v1',JSON.stringify(w));const values=[([0,60,85,95,99][item.rarity]+.1)/100,(tier.indexOf(item)+.1)/tier.length];let n=0;crypto.getRandomValues=a=>{a[0]=Math.floor((values[n++]??.1)*4294967296);return a;};},{slot,id,duplicate});
 await p.locator('.loot-free').click();if(closeDuring)await p.keyboard.press('Escape');await p.evaluate(()=>document.getAnimations().filter(a=>a.effect?.target?.classList.contains('loot-reel')).forEach(a=>a.finish()));
 if(closeDuring){await p.waitForTimeout(100);assert.equal(await p.locator('.loot-reveal[open]').count(),0);await p.getByRole('button',{name:/Open loot box/}).click();}
 await p.waitForSelector('.loot-reveal[open]');assert.equal(await p.locator('.reward-duplicate').textContent(),duplicate?'Duplicate · +1 gold · +1 spin point':'Added to your collection');}
 await spin('character','aria');assert.equal(await p.locator('.reward-confetti i').count(),64);assert.equal(await p.locator('.loot-reveal').getAttribute('data-jumping'),'true');const first=await p.locator('.reward-stage canvas').evaluate(c=>c.toDataURL());await p.waitForTimeout(500);const second=await p.locator('.reward-stage canvas').evaluate(c=>c.toDataURL());assert.notEqual(first,second,'jump pose changes');await p.screenshot({path:'output/aria-legendary-reveal.png'});await p.keyboard.press('Escape');assert(await p.locator('#loot-dialog').isVisible());assert.equal(await p.locator('.game-settings[open]').count(),0);
 await spin('animalHat','fedora',true);assert.equal(await p.locator('.reward-confetti i').count(),0);assert.equal(await p.locator('.loot-reveal').getAttribute('data-jumping'),'false');await p.locator('.loot-reveal h2').click();assert(await p.locator('#loot-dialog').isVisible());
 await spin('costume','maid',false,true);assert.equal(await p.locator('.loot-reveal').getAttribute('data-jumping'),'true');await p.mouse.click(5,5);assert(await p.locator('#loot-dialog').isVisible());await p.keyboard.press('Escape');
 const physics=await p.evaluate(async()=>{const {createLobbyPlayer,stepLobbyPlayer}=await import('/src/game/lobbyPhysics.ts');const p=createLobbyPlayer(1440,900),platform={id:'forged-pedestal',x:0,y:436.5,w:561.6,h:12,type:'stone'};Object.assign(p,{x:1100,y:930,grounded:false,groundedPlatformId:undefined,vy:700});let wrapped=false,landed=false;for(let n=0;n<300;n++){stepLobbyPlayer(p,1/30,1440,900,[platform],true);if(p.y<0)wrapped=true;if(wrapped&&p.grounded){landed=p.groundedPlatformId===platform.id;break;}}return {wrapped,landed,x:p.x,y:p.y};});assert(physics.wrapped&&physics.landed);console.log('Drop',physics);
 await p.evaluate(()=>{const s=window.__FORGE_DEV__.scene.getScene('Menu');s.wallpaperId='starlight';s.background.setTexture('starlight').setDisplaySize(s.scale.width,s.scale.height);s.placeOnPedestal();s.refreshSurfaces();});await p.waitForTimeout(100);await p.screenshot({path:'output/starlight-platform-fixed.png'});
 for(const viewport of [{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(viewport);await p.getByRole('button',{name:/Open loot box/}).click();await spin('character','aria');await p.screenshot({path:'output/reveal-'+viewport.width+'.png'});await p.mouse.click(2,2);await p.keyboard.press('Escape');}
 assert.deepEqual(errors,[]);console.log('PASS rewards, duplicate, nested Back, rarity ordering, 516 sprite frames, drop wrap, mobile reveals');
}finally{await browser.close();}
