import assert from 'node:assert/strict';
import {price,buy,owns,wallet,playableOutfit,lockedPieces} from '../client/src/game/economy';
import {costumeFields} from '../client/src/assets/costumeSets';
const store=new Map<string,string>();Object.assign(globalThis,{localStorage:{getItem:(k:string)=>store.get(k)??null,setItem:(k:string,v:string)=>store.set(k,v)}});
store.set('jump-royale-wallet-v1',JSON.stringify({gold:20,owned:['shirt:steel'],rewards:[]}));
assert.equal(price('costume','steel'),6);assert(buy('costume','steel'));assert.equal(wallet().gold,14);
assert(buy('costume','steel'));assert.equal(wallet().gold,14);assert(owns('costume','steel'));
const outfit={character:'original',...costumeFields('steel')};assert.deepEqual(playableOutfit(outfit),outfit);assert.deepEqual(lockedPieces(outfit),[]);
assert.equal(playableOutfit({character:'original',...costumeFields('mage')}).costume,'classic');
assert.equal(playableOutfit({character:'cat',...costumeFields('mage')}).costume,'classic');
assert(!buy('costume','missing'));assert.equal(wallet().gold,14);
store.set('jump-royale-wallet-v1',JSON.stringify({gold:0,owned:['helmet:mage','shirt:mage','pants:mage'],rewards:[]}));assert(owns('costume','mage'));assert.equal(price('costume','mage'),0);
console.log('PASS complete costume purchase/equip, partial and full legacy ownership credit, locked costume fallback and invalid ID rejection.');
