import assert from 'node:assert/strict';
import {resetWardrobe,restoreWardrobe} from '../client/src/game/wardrobeReset';
import {wallet,buy,owns} from '../client/src/game/economy';
const storage=new Map<string,string>();let fail=false;
Object.assign(globalThis,{localStorage:{getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>{if(fail&&k==='jump-royale-wallet-v1')throw Error('storage');storage.set(k,v);}}});
const initial={gold:50,owned:['character:demon','hair:buns','costume:mushroom','helmet:mage','shirt:mage','pants:mage'],rewards:['match:1'],freeSpins:3,spinPoints:2};
storage.set('jump-royale-wallet-v1',JSON.stringify(initial));
fail=true;assert.equal(resetWardrobe(),false);assert.deepEqual(wallet(),initial);fail=false;
assert(resetWardrobe());assert.deepEqual(wallet().owned,[]);assert.equal(wallet().gold,50);assert.equal(wallet().freeSpins,3);assert.equal(wallet().spinPoints,2);assert(wallet().rewards.includes('match:1'));
assert(!owns('character','mushroom'));assert(!owns('costume','mage'));assert(owns('character','original'));assert(owns('costume','classic'));
assert(buy('character','kangaroo'));assert(resetWardrobe());assert(owns('character','kangaroo'));assert.equal(wallet().gold,45);
assert(restoreWardrobe());for(const id of initial.owned)assert(wallet().owned.includes(id));assert(owns('character','kangaroo'));assert.equal(wallet().gold,45);assert.equal(wallet().freeSpins,3);
assert(restoreWardrobe());assert.equal(new Set(wallet().owned).size,wallet().owned.length);
console.log('PASS: opt-in relock, gold/spins/receipts preserved, legacy unlocks cleared, starter retained, storage failure, idempotence, undo merges new purchases without refunding gold.');
