export const CARDS=[
 {id:'caliber',name:'Heavy Caliber',kind:'WEAPON',rarity:'common',desc:'+30% weapon damage, including sword cuts.',max:5,apply:r=>r.damage*=1.3},
 {id:'trigger',name:'Hair Trigger',kind:'WEAPON',rarity:'common',desc:'Attack 22% faster, including sword cuts.',max:4,apply:r=>r.interval/=1.22},
 {id:'pierce',name:'Armor Piercer',kind:'WEAPON',rarity:'rare',desc:'Each attack hits one more infected per lane.',max:3,apply:r=>r.pierce++},
 {id:'spread',name:'Crossfire',kind:'WEAPON',rarity:'epic',desc:'Every weapon hits your lane and its neighbors.',max:1,eligible:r=>!r.spread,apply:r=>r.spread=1},
 {id:'crit',name:'Headshot',kind:'CRITICAL',rarity:'rare',desc:'+20% critical chance. Critical hits deal double damage.',max:3,apply:r=>r.crit=Math.min(1,r.crit+.2)},
 {id:'headhunter',name:'Headshot Specialist',kind:'CRITICAL',rarity:'rare',desc:'+10% critical chance and +50% critical damage. Works with cuts too.',max:2,apply:r=>{r.crit=Math.min(1,r.crit+.1);r.critDamage+=.5;}},
 {id:'ice',name:'Ice Attunement',kind:'ICE',rarity:'rare',desc:'Weapon hits chill for 3s. Infected approach 40% slower.',max:1,apply:r=>r.chill=.4},
 {id:'fire',name:'Fire Attunement',kind:'FIRE',rarity:'rare',desc:'+50% all fire damage. Every weapon burns for 18 damage/s for 2.4s.',max:1,apply:r=>{r.fireBonus+=.5;r.burn+=18;}},
 {id:'air',name:'Air Attunement',kind:'AIR',rarity:'rare',desc:'Double jump height. Leap over every infected, including brutes.',max:1,apply:r=>r.jumpPower*=Math.SQRT2},
 {id:'earth',name:'Earth Attunement',kind:'THORNS',rarity:'rare',desc:'Ram infected for 150 thorns damage. Contact still hurts you.',max:1,apply:r=>r.thorns+=150},
 {id:'burn',name:'Incendiary',kind:'FIRE',rarity:'rare',desc:'Weapon hits burn for +18 damage/s. Starts or strengthens a fire build.',max:3,apply:r=>r.burn+=18},
 {id:'bellows',name:'Fan the Flames',kind:'FIRE',rarity:'rare',desc:'+40% all fire damage and +1.2s burn duration.',max:3,eligible:r=>r.burn>0,apply:r=>{r.fireBonus+=.4;r.burnDuration+=1.2;}},
 {id:'wildfire',name:'Wildfire',kind:'FIRE',rarity:'epic',desc:'Burning kills explode for 45 fire damage and ignite nearby infected.',max:2,eligible:r=>r.burn>0,apply:r=>r.wildfire+=45},
 {id:'firebomb',name:'Firebomb',kind:'FIRE',rarity:'rare',desc:'Grenades become fire damage and ignite survivors. Gain 2 grenades.',max:1,eligible:r=>r.burn>0,apply:r=>{r.fireGrenades=true;r.grenades=Math.min(9,r.grenades+2);}},
 {id:'cinders',name:'Cinder Feast',kind:'FIRE',rarity:'rare',desc:'Burning kills restore 3 health.',max:2,eligible:r=>r.burn>0,apply:r=>r.fireLeech+=3},
 {id:'thorns',name:'Briar Armor',kind:'THORNS',rarity:'rare',desc:'+60 thorns contact damage and 12% less damage taken.',max:3,apply:r=>{r.thorns+=60;r.armor*=.88;}},
 {id:'juggernaut',name:'Juggernaut',kind:'THORNS',rarity:'rare',desc:'+40 max health; heal 40. Thorns also deal 30% of max health.',max:3,eligible:r=>r.thorns>0,apply:r=>{r.maxHp+=40;r.hp+=40;r.thornScaling+=.3;}},
 {id:'retribution',name:'Retribution',kind:'THORNS',rarity:'epic',desc:'Ramming an infected deals 50% of your thorns damage to nearby infected.',max:1,eligible:r=>r.thorns>0,apply:r=>r.retribution=true},
 {id:'bulwark',name:'Living Fortress',kind:'THORNS',rarity:'rare',desc:'Take 15% less damage. Regenerate 2 health/s while below half health.',max:2,eligible:r=>r.thorns>0,apply:r=>{r.armor*=.85;r.regen+=2;}},
 {id:'vital',name:'Hard to Kill',kind:'SURVIVOR',rarity:'common',desc:'+25 maximum health. Recover 25 health.',max:4,apply:r=>{r.maxHp+=25;r.hp+=25;}},
 {id:'armor',name:'Scrap Armor',kind:'SURVIVOR',rarity:'rare',desc:'Take 18% less damage.',max:3,apply:r=>r.armor*=.82},
 {id:'medic',name:'Field Medic',kind:'SURVIVOR',rarity:'common',desc:'Recover 45 health right now.',max:99,eligible:r=>r.hp<r.maxHp-10,apply:r=>r.hp=Math.min(r.maxHp,r.hp+45)},
 {id:'leech',name:'Blood Rebate',kind:'SURVIVOR',rarity:'epic',desc:'Every kill restores 2 health.',max:2,apply:r=>r.leech+=2},
 {id:'ghost',name:'Ghost Step',kind:'SURVIVOR',rarity:'rare',desc:'The horde gains ground 25% slower.',max:3,apply:r=>r.chaseRate*=.75},
 {id:'grenade',name:'Last Resort',kind:'EQUIPMENT',rarity:'common',desc:'+2 grenades. Grenades hit 40% harder.',max:4,apply:r=>{r.grenades=Math.min(9,r.grenades+2);r.blast*=1.4;}},
 {id:'scavenge',name:'Scavenger',kind:'EQUIPMENT',rarity:'common',desc:'Supply pickups heal 10 more and push the horde back.',max:3,apply:r=>r.scavenge+=10},
 {id:'rations',name:'Emergency Rations',kind:'SURVIVOR',rarity:'common',desc:'Heal 15 at each new district, and now.',max:3,apply:r=>{r.rations+=15;r.hp=Math.min(r.maxHp,r.hp+15);}},
 {id:'reroll',name:'Lucky Find',kind:'EQUIPMENT',rarity:'rare',desc:'+2 card rerolls and one grenade.',max:2,apply:r=>{r.rerolls+=2;r.grenades=Math.min(9,r.grenades+1);}},
 {id:'reserves',name:'Last Supplies',kind:'EQUIPMENT',rarity:'common',desc:'Build complete. Recover 25 health and gain one grenade.',max:Infinity,eligible:()=>false,apply:r=>{r.hp=Math.min(r.maxHp,r.hp+25);r.grenades=Math.min(9,r.grenades+1);}}
];
