import {Run,CARDS,WEAPONS,DISTRICTS,SECTOR_LENGTH,LANES,MAPS,xpRequired} from './model.mjs';
import {replacementStats} from './arsenal.mjs';
import {POWERUPS,difficultyAt} from './endless.mjs';
import {normalizeProfile,runReward} from './progression.mjs';
import {createSkillTree} from './skill-tree.mjs';
import {createRenderer} from './renderer.mjs';
import {crumblePieces} from './animation.mjs';
import {ASSETS,CARD_ART,assetUrl} from './visuals.mjs';
const $=id=>document.getElementById(id),canvas=$('game');
let W=640,H=400,mode='loading',run=new Run(91),weapon='carbine',map='dead-city',last=0,ambient=0,shake=0,flash=0,toastTime=0,xpPulse=0,saved=false;
let best=0,totalKills=0,muted=false,profile=normalizeProfile(),skillsReturn='title',earned=0;const images={},effects=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const renderer=createRenderer(canvas,images,reduced);
try{const d=JSON.parse(localStorage.getItem('dead-run-v1')||'{}');best=Number.isFinite(d.best)?Math.max(0,d.best):0;totalKills=Number.isFinite(d.kills)?Math.max(0,d.kills):0;muted=!!d.muted;profile=normalizeProfile(d.progression);}catch{}
function persist(){try{localStorage.setItem('dead-run-v1',JSON.stringify({best,kills:totalKills,muted,progression:profile}));}catch{toast('Storage unavailable. Progress lasts until this page closes.');}}
const skillTree=createSkillTree(()=>profile,()=>{persist();personal();audio.effect('upgrade');});
function bankRun(){if(saved)return;earned=runReward(run);if(!run.testRun){best=Math.max(best,Math.floor(run.distance));totalKills+=run.kills;profile.scrap+=earned;if(run.time>0)profile.runs++;persist();}saved=true;personal();}
function openSkills(){if(!['title','ended'].includes(mode))return;skillsReturn=mode;skillTree.render();showMode('skills');$('close-skills').focus();}
function closeSkills(){showMode(skillsReturn);$(skillsReturn==='ended'?'end-skills':'open-skills').focus();}
function districtName(){return DISTRICTS[run.sector%DISTRICTS.length]+' · '+(run.sector+1);}
function powerHud(){
 for(const [kind,power] of Object.entries(POWERUPS)){const timer=run.powers[kind],chip=$('power-'+kind);chip.hidden=timer<=0;chip.querySelector('b').textContent=Math.ceil(timer)+'s';chip.querySelector('i').style.transform=`scaleX(${Math.min(1,timer/(power.duration*run.powerDuration))})`;}
 $('weapon-label').textContent=run.activeMinigun?'MINIGUN':WEAPONS[run.weapon].name.toUpperCase();const art=run.activeMinigun?'minigun':'weapon-'+run.weapon;if($('weapon-image').dataset.art!==art){$('weapon-image').src=assetUrl(art);$('weapon-image').dataset.art=art;}
}
for(const [kind,power] of Object.entries(POWERUPS)){const chip=document.createElement('div');chip.className='power-chip';chip.id='power-'+kind;chip.style.setProperty('--power-color',power.color);chip.innerHTML=`<img src="${assetUrl(kind)}" alt=""><span>${power.name}</span><b></b><i></i>`;$('powers').append(chip);}
function personal(){$('wallet').textContent=profile.scrap.toLocaleString();$('best').textContent=Math.floor(best).toLocaleString();$('total-kills').textContent=totalKills.toLocaleString();$('sound').innerHTML=`<img src="${assetUrl(muted?'control-muted':'control-sound')}" alt=""><span>SOUND ${muted?'OFF':'ON'}</span>`;$('sound').setAttribute('aria-label',muted?'Enable audio':'Mute audio');$('sound').setAttribute('aria-pressed',String(muted));}personal();
class Sound{
 start(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=.16;this.master.connect(this.ctx.destination);}this.ctx.resume().catch(()=>{});}catch{}}
 tone(f,d=.08,type='triangle',volume=.2,slide=0){if(!this.ctx||muted)return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(slide,t+d);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+d);o.onended=()=>{o.disconnect();g.disconnect();};}
 effect(type){if(type==='shot'||type==='rearShot'){this.tone(110,.08,'sawtooth',.24,30);this.tone(600,.028,'square',.08,90);}if(type==='hurt')this.tone(80,.23,'sawtooth',.4,22);if(type==='grenade'){this.tone(70,.5,'sawtooth',.6,12);this.tone(240,.13,'square',.3,30);}if(type==='supply'||type==='upgrade'){this.tone(440,.12,'triangle',.3);setTimeout(()=>this.tone(660,.16,'triangle',.2),90);}if(type==='jump')this.tone(130,.1,'triangle',.12,230);if(type==='death')this.tone(160,.8,'sawtooth',.3,20);if(type==='levelup'||type==='win'){this.tone(220,.5,'triangle',.3);setTimeout(()=>this.tone(330,.5,'triangle',.25),170);}}
 tick(){if(mode!=='playing'||muted)return;if(!this.next||run.time>this.next){this.next=run.time+.65;this.tone(run.sector%2?49:55,.35,'triangle',.12);if(Math.floor(run.time*2)%4===0)this.tone(83,.12,'sine',.25,27);}}
}const audio=new Sound();
function resize(){const b=$('stage').getBoundingClientRect();W=b.width<600?360:720;H=Math.round(W*b.height/b.width);renderer.resize(W,H);}
new ResizeObserver(resize).observe($('stage'));resize();
function render(){renderer.render(run,{mode,ambient,shake,flash,effects});}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');toastTime=2.8;}
function deckText(){return Object.entries(run.deck).map(([id,n])=>CARDS.find(c=>c.id===id).name+(n>1?' ×'+n:'')).join(' · ')||'No upgrades collected';}
function updateBuild(){$('build').replaceChildren(...Object.entries(run.deck).map(([id,n])=>{const c=CARDS.find(c=>c.id===id),s=document.createElement('span');s.innerHTML=`<img src="${assetUrl(CARD_ART[id])}" alt="">${n>1?'<b>'+n+'</b>':''}`;s.dataset.build=c.kind.toLowerCase();s.title=c.name+(n>1?' ×'+n:'')+' · '+c.desc;return s;}));}
function hud(){
 $('health-label').textContent=Math.ceil(run.hp)+' / '+run.maxHp;$('health').style.width=run.hp/run.maxHp*100+'%';$('health').style.background=run.hp<30?'#d56638':'#c4c98c';$('distance').innerHTML=Math.floor(run.distance).toLocaleString()+' <small>m</small>';$('district').textContent=districtName();$('progress').style.width=(run.distance%SECTOR_LENGTH)/SECTOR_LENGTH*100+'%';$('kills').textContent=String(run.kills).padStart(2,'0');$('grenade-count').textContent=run.grenades+' GRENADES · E';$('touch-grenades').textContent=run.grenades;$('chase').style.width=run.chase+'%';$('chase-label').textContent=run.chase>75?'CLOSE':run.chase>45?'APPROACHING':'DISTANT';$('weapon-range').textContent=run.activeMinigun?'190 M · ALL LANES':run.range+' M · '+(run.spread?'UP TO 3 LANES':'1 LANE');powerHud();const d=difficultyAt(run.time);$('run-clock').textContent=Math.floor(run.time/60)+':'+String(Math.floor(run.time%60)).padStart(2,'0');$('threat-label').textContent=d.surge?'HORDE SURGE':'THREAT '+(d.tier+1);$('speed-label').textContent=run.speed.toFixed(1)+' M/S';$('run-status').classList.toggle('surge',d.surge);$('practice-label').hidden=!run.testRun;
 const needed=xpRequired(run.level);$('level-label').textContent='LEVEL '+run.level;$('xp-label').textContent=run.xp+' / '+needed+' XP';$('xp-fill').style.width=Math.min(100,run.xp/needed*100)+'%';$('xp-meter').setAttribute('aria-valuenow',Math.min(needed,run.xp));$('xp-meter').setAttribute('aria-valuemax',needed);$('xp-hud').classList.toggle('pulse',xpPulse>0);
 const killLane=LANES.indexOf(run.killLaneAt());$('kill-lane-label').textContent='KILL LANE '+(killLane+1);[...document.querySelectorAll('.lane-dots i')].forEach((el,i)=>el.classList.toggle('active',i===killLane));
}
function weaponCrate(){
 showMode('crate');$('crate-current').textContent='Equipped: '+WEAPONS[run.weapon].name;$('crate-build').textContent=deckText();
 $('weapon-offers').replaceChildren(...run.weaponChoices.map((id,i)=>{const w=WEAPONS[id],stats=replacementStats(run,id),b=document.createElement('button');b.className='card rare weapon-offer';b.dataset.offer=id;
  b.setAttribute('aria-label','Equip '+w.name);b.innerHTML=`<span class="card-top"><span>WEAPON CRATE</span><span>[ ${i+1} ]</span></span><img class="weapon-art" src="${assetUrl('weapon-'+id)}" alt=""><strong class="card-name">${w.name}</strong><span class="card-desc">${w.description}</span><span class="weapon-stats">${Math.round(stats.damage)} DMG · ${(1/stats.interval).toFixed(1)}/s<br>${stats.range} M · ${stats.pierce} TARGETS / LANE</span><span class="card-bottom">EQUIP →</span>`;b.onclick=()=>chooseWeapon(id);return b;}));
 $('keep-weapon').textContent='[ 4 ] KEEP '+WEAPONS[run.weapon].name.toUpperCase();$('weapon-offers').firstElementChild?.focus();
}
function chooseWeapon(id){if(!run.chooseWeapon(id))return;showMode('playing');events();hud();if(mode==='playing')canvas.focus();}
function showMode(next){mode=next;document.body.dataset.mode=next;for(const [id,m]of [['intro','title'],['pause-screen','paused'],['end-screen','ended'],['draft','draft'],['skills-screen','skills'],['weapon-crate','crate']])$(id).hidden=next!==m;for(const id of ['hud','chase-hud','build','xp-hud','kill-lane','run-status','powers'])$(id).hidden=!['playing','paused','draft','crate'].includes(next);$('touch-controls').hidden=next!=='playing';$('test-gear').hidden=next!=='playing';$('pause').disabled=next!=='playing'&&next!=='paused';$('pause').setAttribute('aria-label',next==='paused'?'Resume game':'Pause game');$('pause').innerHTML=`<img src="${assetUrl(next==='paused'?'control-play':'control-pause')}" alt="">`;}
function start(){if(['playing','paused','draft','crate'].includes(mode))bankRun();run=new Run((Date.now()^Math.floor(Math.random()*1e9))>>>0,weapon,map,profile);earned=0;effects.length=0;saved=false;shake=flash=xpPulse=0;audio.start();audio.next=0;$('weapon-label').textContent=WEAPONS[weapon].name.toUpperCase();$('weapon-image').src=assetUrl('weapon-'+weapon);updateBuild();showMode('playing');hud();canvas.focus();toast('NO EXTRACTION. MAKE THIS RUN COUNT.');}
function draft(){showMode('draft');$('sector-number').textContent=String(run.level);$('draft-summary').textContent=`${run.kills} kills · ${run.totalXp} XP earned`;$('deck-summary').textContent=deckText();$('cards').replaceChildren(...run.choices.map((id,i)=>{const c=CARDS.find(c=>c.id===id),b=document.createElement('button');b.className='card '+c.rarity;b.dataset.build=c.kind.toLowerCase();b.setAttribute('aria-label',`Choose ${c.name}: ${c.desc}`);b.innerHTML=`<span class="card-top"><span>${c.kind}</span><span>${c.rarity.toUpperCase()}</span></span><img class="card-icon" src="${assetUrl(CARD_ART[c.id])}" alt=""><strong class="card-name">${c.name}</strong><span class="card-desc">${c.desc}</span><span class="card-bottom"><span>${run.deck[id]?'STACK '+(run.deck[id]+1):'NEW UPGRADE'}</span><span>[ ${i+1} ] TAKE IT →</span></span>`;b.onclick=()=>choose(id);return b;}));$('reroll').innerHTML=`<img src="${assetUrl('control-reroll')}" alt=""><span>REROLL · ${run.rerolls} LEFT</span>`;$('reroll').disabled=run.rerolls===0;$('cards').firstElementChild?.focus();}
function choose(id){if(!run.choose(id))return;updateBuild();events();if(!run.drafting){showMode('playing');canvas.focus();}hud();toast(CARDS.find(c=>c.id===id).name.toUpperCase());}
function end(){const record=!run.testRun&&run.distance>best;bankRun();showMode('ended');$('end-eyebrow').textContent=run.testRun?'PRACTICE RUN':record?'NEW DISTANCE RECORD':'RUN ENDED';$('end-title').innerHTML='THE DEAD<br><em>DON’T STOP.</em>';$('end-tip').textContent=run.reason;$('end-distance').textContent=Math.floor(run.distance).toLocaleString();$('end-kills').textContent=run.kills;$('end-cards').textContent=Object.values(run.deck).reduce((a,b)=>a+b,0);$('end-deck').textContent=deckText();$('end-reward').textContent=run.testRun?'Practice: no scrap or records saved.':'+'+earned+' SCRAP · '+profile.scrap+' BANKED';$('retry').focus();}
function pause(){if(mode==='playing'){showMode('paused');$('resume').focus();}else if(mode==='paused'){showMode('playing');canvas.focus();}}
function events(){let gunSound=false;for(const e of run.events.splice(0)){
 if(e.type==='shot'||e.type==='rearShot'){effects.push({...e,life:.10});if(!gunSound){audio.effect(e.type);gunSound=true;}}
 else audio.effect(e.type);
 if(['slash','wildfire','thorns'].includes(e.type)){effects.push({...e,life:e.type==='slash'?.28:.4});if(e.type==='slash')audio.tone(600,.12,'sawtooth',.16,90);}
 if(e.type==='weaponcrate')weaponCrate();if(e.type==='weaponchange')toast(e.name.toUpperCase()+' · BUILD PRESERVED');
 if(e.type==='kill'){
  xpPulse=.4;const at=run.distance+e.z;
  effects.push({type:'burst',lane:e.lane,at,elevation:e.elevation,brute:e.brute,life:.55},{type:'stain',lane:e.lane,at,elevation:e.elevation,variant:Math.random()<.5,life:7},{type:'xpMote',lane:e.lane,at,elevation:e.elevation,life:.8});
  for(let i=0;i<(reduced?0:run.activeMinigun?3:e.brute?12:7);i++)effects.push({type:'blood',lane:e.lane,at,elevation:e.elevation,dx:0,dy:30,vx:(Math.random()-.5)*100,vy:20+Math.random()*60,life:.65});
 }
 if(e.type==='land')shake=Math.max(shake,1.4);
 if(e.type==='crush'){const at=run.distance+e.z;effects.push(...crumblePieces({...e,at},Math.random,reduced));if(!reduced)effects.push({type:'dust',lane:e.lane,at,elevation:e.elevation,life:.6});audio.tone(95,.15,'sawtooth',.15,25);}
 if(e.type==='hurt'){shake=6;flash=1;}if(e.type==='grenade'){shake=10;for(const lane of LANES)effects.push({type:'blast',lane,life:.48});}if(e.type==='supply')toast('HEALTH RESTORED');if(e.type==='levelup')draft();if(e.type==='district')toast(districtName());if(e.type==='surge')toast('HORDE SURGE · KEEP MOVING');if(e.type==='powerup'){toast(POWERUPS[e.kind].name+' · '+POWERUPS[e.kind].desc);audio.effect('upgrade');}if(e.type==='crush')shake=Math.max(shake,2);if(e.type==='death'||e.type==='win')end();
}}
function frame(t){if(effects.length>500)effects.splice(0,effects.length-500);const dt=Math.min(.05,(t-last)/1000||0);last=t;ambient+=dt;if(mode==='playing'){run.update(dt);events();audio.tick();hud();}if(mode!=='paused'&&mode!=='draft'&&mode!=='crate'){for(const e of effects){e.life-=dt;if(e.type==='blood'||e.type==='crumble'){e.dx+=e.vx*dt;e.dy+=e.vy*dt;e.vy-=160*dt;if(e.type==='crumble')e.angle+=e.spin*dt;}}for(let i=effects.length-1;i>=0;i--)if(effects[i].life<=0||(effects[i].at!==undefined&&effects[i].at<run.distance-8))effects.splice(i,1);shake=Math.max(0,shake-dt*25);flash=Math.max(0,flash-dt*3);xpPulse=Math.max(0,xpPulse-dt);}toastTime-=dt;if(toastTime<=0)$('toast').classList.remove('visible');render();requestAnimationFrame(frame);}
for(const button of document.querySelectorAll('[data-weapon]'))button.onclick=()=>{weapon=button.dataset.weapon;for(const b of document.querySelectorAll('[data-weapon]')){b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));}};
for(const button of document.querySelectorAll('[data-map]'))button.onclick=()=>{if(MAPS.some(m=>m.id===button.dataset.map)){map=button.dataset.map;for(const b of document.querySelectorAll('[data-map]')){b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button));}}};
$('start').onclick=start;$('retry').onclick=start;$('pause-retry').onclick=start;$('resume').onclick=pause;$('pause').onclick=pause;
for(const id of ['pause-home','end-home'])$(id).onclick=()=>{if(mode==='paused')bankRun();personal();showMode('title');$('start').focus();};
$('open-skills').onclick=openSkills;$('end-skills').onclick=openSkills;$('close-skills').onclick=closeSkills;
for(const button of document.querySelectorAll('[data-power]'))button.onclick=()=>{if(mode!=='playing')return;run.activatePowerup(button.dataset.power,true);events();hud();canvas.focus();};
$('keep-weapon').onclick=()=>chooseWeapon('keep');$('test-crate').onclick=()=>{if(mode==='playing'&&run.openWeaponCrate(true))events();};
$('reroll').onclick=()=>{if(run.reroll())draft();};$('sound').onclick=()=>{muted=!muted;audio.start();personal();persist();};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('stage').requestFullscreen)await $('stage').requestFullscreen();else toast('Fullscreen is unavailable in this browser.');}catch{toast('Fullscreen is unavailable in this browser.');}};
document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'Exit fullscreen':'Enter fullscreen');resize();});
function action(name){if(mode==='playing'){run.action(name);events();hud();}}
window.addEventListener('keydown',e=>{if(mode==='crate'){
 if(['1','2','3','4'].includes(e.key)){e.preventDefault();chooseWeapon(e.key==='4'?'keep':run.weaponChoices[+e.key-1]);}
 if(e.key==='Tab'){const focus=[...$('weapon-crate').querySelectorAll('button')],idx=focus.indexOf(document.activeElement);if(e.shiftKey&&idx<=0){e.preventDefault();focus.at(-1)?.focus();}else if(!e.shiftKey&&idx===focus.length-1){e.preventDefault();focus[0]?.focus();}}return;
 }if(mode==='skills'){if(e.key==='Escape'){e.preventDefault();closeSkills();}if(e.key==='Tab'){const focus=[...$('skills-screen').querySelectorAll('button:not(:disabled)')].filter(b=>b.getClientRects().length),idx=focus.indexOf(document.activeElement);if(e.shiftKey&&idx<=0){e.preventDefault();focus.at(-1)?.focus();}else if(!e.shiftKey&&idx===focus.length-1){e.preventDefault();focus[0]?.focus();}}return;}if(mode==='draft'){if(['1','2','3'].includes(e.key)){e.preventDefault();choose(run.choices[+e.key-1]);}if(e.key==='Tab'){const focus=[...$('draft').querySelectorAll('button:not(:disabled)')],idx=focus.indexOf(document.activeElement);if(e.shiftKey&&idx<=0){e.preventDefault();focus.at(-1)?.focus();}else if(!e.shiftKey&&idx===focus.length-1){e.preventDefault();focus[0]?.focus();}}return;}if(['p','P','Escape'].includes(e.key)){e.preventDefault();pause();return;}if(mode!=='playing'||e.repeat)return;const map={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',w:'jump',W:'jump',' ':'jump',ArrowDown:'roll',s:'roll',S:'roll',e:'grenade',E:'grenade'};if(map[e.key]){e.preventDefault();action(map[e.key]);}});
for(const b of document.querySelectorAll('[data-action]'))b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action);});
let touch=null;canvas.addEventListener('pointerdown',e=>{if(mode!=='playing')return;touch={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))<22)action('jump');else if(Math.abs(dx)>Math.abs(dy))action(dx>0?'right':'left');else action(dy>0?'roll':'jump');});canvas.addEventListener('pointercancel',()=>touch=null);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});window.addEventListener('blur',()=>{if(mode==='playing')pause();});
window.deadRun={snapshot:()=>({mode,weaponChoices:[...run.weaponChoices],crit:run.crit,critDamage:run.critDamage,thorns:run.thornsDamage,burn:run.burn,fireBonus:run.fireBonus,chill:run.chill,time:run.time,speed:run.speed,testRun:run.testRun,powers:{...run.powers},progression:structuredClone(profile),reward:runReward(run),damageMultiplier:run.damageMultiplier,map:run.map,lanes:[...LANES],xp:run.xp,xpNeeded:xpRequired(run.level),totalXp:run.totalXp,level:run.level,killLane:run.killLaneAt(),killLanes:run.killLanes.map(k=>({...k})),effects:effects.map(e=>({type:e.type,life:e.life})),weapon:run.weapon,seed:run.seed,distance:run.distance,lane:run.lane,x:run.x,y:run.y,elevation:run.elevation,grounded:run.grounded,stride:run.stride,airTime:run.airTime,jumping:run.jumping,landing:run.landing,supportHeight:run.supportHeight,aim:run.aim,firePose:run.firePose,roofTime:run.roofTime,range:run.range,roll:run.roll,hp:run.hp,maxHp:run.maxHp,chase:run.chase,kills:run.kills,grenades:run.grenades,sector:run.sector,deck:{...run.deck},choices:[...run.choices],rerolls:run.rerolls,damage:run.damage,interval:run.interval,best,totalKills,assets:Object.keys(images).length,expectedAssets:Object.keys(ASSETS).length,scenery:{...renderer.stats},platforms:run.platforms.filter(p=>p.end>run.distance-24&&p.at<run.distance+240).map(p=>({...p,z:p.at-run.distance,endZ:p.end-run.distance})),entities:run.entities.map(e=>({kind:e.kind,lane:e.lane,z:e.at-run.distance,hp:e.hp,chilled:e.chilled,burning:e.burning,elevation:e.elevation||0}))})};
async function load(){try{await Promise.all(Object.entries(ASSETS).map(([name,url])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[name]=im;resolve();};im.onerror=()=>reject(new Error(name));im.src=url;})));$('start').disabled=false;$('start-label').textContent='START RUN';$('load-status').textContent='';$('start').onclick=start;showMode('title');}catch{$('start-label').textContent='RETRY LOADING';$('load-status').textContent='Some art could not load. Tap to try again.';$('start').disabled=false;$('start').onclick=load;}}
load();requestAnimationFrame(frame);
