import './style.css';
import {Expedition,TOWERS,SECTORS,BOONS,dist,clamp} from './engine.js';
import {Renderer} from './renderer.js';
const $=s=>document.querySelector(s),app=$('#app'),renderer=new Renderer($('#field'));
const storage={get(k,f=null){try{return localStorage.getItem('deadroad2.'+k)||f;}catch{return f;}},set(k,v){try{localStorage.setItem('deadroad2.'+k,v);}catch{}},remove(k){try{localStorage.removeItem('deadroad2.'+k);}catch{}}};
let game=new Expedition(),screen='menu',rig='warden',difficulty='standard',selection=null,selectedTower=null,targeting=false,speed=1,keys=new Set(),last=performance.now(),hudClock=0,toastTimer,drag=null,touchVector={x:0,y:0};
let audioOn=storage.get('sound','on')==='on',reduced=storage.get('motion','on')==='off',audio,master,lastShot=0;
renderer.reduced=reduced;document.body.classList.toggle('reduced',reduced);
function sound(kind){if(!audioOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();if(!master){master=audio.createGain();master.gain.value=.12;master.connect(audio.destination);}if(kind==='shot'&&audio.currentTime-lastShot<.08)return;if(kind==='shot')lastShot=audio.currentTime;let o=audio.createOscillator(),v=audio.createGain(),t=audio.currentTime;const notes={shot:[160,50,.065],build:[330,660,.13],clear:[440,880,.4],hit:[85,35,.12],strike:[70,25,.5],pulse:[620,120,.4],salvage:[660,990,.17],wave:[180,100,.4],repair:[240,520,.22],boss:[110,55,.5],bossDown:[180,560,.5],won:[520,1040,.6],lost:[150,40,.8]};let [a,b,len]=notes[kind]||[360,480,.1];o.type=kind==='shot'||kind==='strike'?'sawtooth':'sine';o.frequency.setValueAtTime(a,t);o.frequency.exponentialRampToValueAtTime(b,t+len);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(.5,t+.01);v.gain.exponentialRampToValueAtTime(.0001,t+len);o.connect(v);v.connect(master);o.start(t);o.stop(t+len);}catch{}}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3400);}
function button(action,text,cls='',extra=''){return `<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;}
function icon(name){return {pause:'Ⅱ',map:'⌁',sound:audioOn?'♪':'♩'}[name]||name;}
function checkpoint(){if(['build','convoy'].includes(game.phase))storage.set('save',game.serialize());}
function showMenu(){screen='menu';selection=null;selectedTower=null;targeting=false;document.body.classList.add('menu-open');app.innerHTML=`<section class="landing"><header class="landing-top"><a href="../games.html" class="vault-link">↖ ARIA & FRIENDS</a><span class="edition">AN ORIGINAL ROADWATCH EXPEDITION</span>${button('sound',icon('sound'),'icon-button','aria-label="Toggle audio"')}</header><div class="hero-copy"><div class="eyebrow"><i class="live-dot"></i> THE ROAD DOESN’T END HERE</div><h1>DEADROAD<span class="io">.IO</span><span class="two">2</span></h1><div class="subtitle"><span></span> LAST LIGHT <span></span></div><p class="intro">The world went quiet.<br>Give it something to fight for.</p><p class="premise">One convoy. Three lost sectors. Build your defenses,<br class="desktop"> break the horde, and bring the last relay online.</p><div class="menu-start">${button('begin','START EXPEDITION <span>↗</span>','primary large')}${storage.get('save')?button('continue','CONTINUE EXPEDITION <span>→</span>','secondary large'):''}</div><div class="menu-links">${button('help','FIELD MANUAL')}${button('settings','SETTINGS')}<a href="./legacy.html?offline=1">ORIGINAL SANDBOX ↗</a></div><div class="record"><span>PERSONAL BEST</span><strong>${Number(storage.get('best',0)).toLocaleString()} <small>PTS</small></strong></div></div><div class="hero-coordinate"><i></i><div>38° 36′ N &nbsp; 90° 12′ W<small>OZARK EXCLUSION ZONE / DUSK</small></div></div><footer class="landing-footer"><span><b>01</b> DRIVE & SALVAGE</span><span><b>02</b> DEPLOY & DEFEND</span><span><b>03</b> RECLAIM THE ROAD</span><small>SINGLE PLAYER · SAVED ON THIS DEVICE</small></footer></section>`;}
function modal(kicker,title,body,footer='',cls=''){app.innerHTML=`<section class="scrim"><div class="modal ${cls}"><div class="modal-header"><div><div class="eyebrow">${kicker}</div><h2>${title}</h2></div>${button('back','×','icon-button','aria-label="Close"')}</div>${body}${footer?`<footer class="modal-footer">${footer}</footer>`:''}</div></section>`;app.querySelector('button')?.focus();}
function setup(){screen='setup';modal('LOADOUT // BEFORE THE ROAD','Choose your convoy.',`<p class="muted">Every rig can make it. Decide how you’ll get there.</p><div class="rigs">${[{id:'warden',name:'Roadwarden',tag:'BALANCED',stat:'300 scrap · 1,000 hull',desc:'A steady hand for an unsteady world. The recommended first expedition.'},{id:'bastion',name:'Iron Bastion',tag:'SURVIVAL',stat:'300 scrap · 1,200 hull',desc:'Reinforced armor buys time when the front line breaks.'},{id:'scout',name:'Scavenger',tag:'ECONOMY',stat:'370 scrap · +20% salvage',desc:'Turn the wreckage into an arsenal. More scrap from every kill.'}].map((r,i)=>`<button class="rig ${rig===r.id?'active':''}" data-action="rig:${r.id}"><small>0${i+1} / ${r.tag}</small><img src="./assets/generated/base/base_mobile_command_core${i===1?'_damaged':i===2?'_packed':''}.png" alt=""><h3>${r.name}</h3><strong>${r.stat}</strong><p>${r.desc}</p><span class="choose-mark">${rig===r.id?'● SELECTED':'○ SELECT RIG'}</span></button>`).join('')}</div><div class="difficulty"><span>THREAT LEVEL</span>${['story','standard','veteran'].map(d=>button('difficulty:'+d,d.toUpperCase(),difficulty===d?'active':'')).join('')}</div><p class="small muted">${difficulty==='story'?'Story: enemies have 28% less health and impact damage.':difficulty==='veteran'?'Veteran: enemies have 30% more health and impact damage.':'Standard: the intended balance. Plan, adapt, survive.'}</p>`,button('launch','TAKE THE ROAD <span>→</span>','primary'));
}
function start(resume=false){try{game=resume?Expedition.restore(storage.get('save')):new Expedition({rig,difficulty});}catch{storage.remove('save');toast('That checkpoint could not be loaded. A fresh road awaits.');setup();return;}renderer.sector=-1;renderer.zoom=1;renderer.offset={x:0,y:0};screen='game';speed=1;keys.clear();selection=null;selectedTower=null;targeting=false;document.body.classList.remove('menu-open');renderHud();checkpoint();sound('build');if(!resume)toast('WASD to drive. Collect the glowing scrap crates, then deploy with E.');}
function renderHud(){screen='game';document.body.classList.remove('menu-open');let s=SECTORS[game.sector],convoy=game.phase==='convoy';app.innerHTML=`<header class="topbar"><div class="wordmark">DEADROAD<span>.IO</span> <b>2</b></div><div class="sector-label"><small>SECTOR 0${game.sector+1} / 03</small><strong>${s.name}</strong></div><div class="resources"><div class="hull"><span>CONVOY HULL</span><strong id="hull-value"></strong><div class="meter"><i id="hull-fill"></i></div></div><div class="scrap"><span>◇ SCRAP</span><strong id="scrap-value"></strong></div><div class="wave-stat"><span>WAVE</span><strong id="wave-value"></strong></div></div><nav>${button('map','⌁','icon-button','aria-label="Expedition map" title="Expedition map (M)"')}${button('pause','Ⅱ','icon-button','aria-label="Pause game" title="Pause (Escape)"')}</nav></header>
<aside class="mission"><div class="eyebrow"><i class="live-dot"></i> <span id="phase-label"></span></div><h2 id="mission-title"></h2><p id="mission-desc"></p><div id="wave-progress" class="meter"><i id="wave-fill"></i></div><span id="hostiles"></span></aside>
<div class="battle-banner" id="battle-banner"></div><div class="view-controls">${button('zoom-out','−','icon-button','aria-label="Zoom out"')}${button('focus','⌖','icon-button','aria-label="Reset camera" title="Reset view (F)"')}${button('zoom-in','+','icon-button','aria-label="Zoom in"')}</div>
<aside class="tower-inspector" id="inspector" hidden></aside>
<div class="support ${convoy?'inactive':''}"><small>FIELD SUPPORT</small>${button('strike','<span>✳</span><b>AIRSTRIKE</b><small id="strike-cd">Q · READY</small>','','title="Q: select an airstrike target. 36-second cooldown."')}${button('pulse','<span>ϟ</span><b>EMP PULSE</b><small id="pulse-cd">R · READY</small>','','title="R: slow enemies near the convoy. 24-second cooldown."')}${button('repair','<span>＋</span><b>REPAIR</b><small>65 ◇ · +250 HULL</small>','','title="Repair 250 hull for 65 scrap"')}</div>
<section class="bottom-area">${convoy?`<div class="convoy-panel"><div class="convoy-symbol">↟</div><div><div class="eyebrow">MOBILE COMMAND</div><h3>Find your ground.</h3><p>Collect scrap. Choose a position. Deploy your defenses.</p></div>${button('deploy','DEPLOY BASE <kbd>E</kbd>','primary')}</div><div class="touch-drive" aria-label="Touch drive controls">${button('drive:up','↑','','aria-label="Drive north"')}${button('drive:left','←','','aria-label="Drive west"')}${button('drive:down','↓','','aria-label="Drive south"')}${button('drive:right','→','','aria-label="Drive east"')}</div>`:`<div class="dock-top"><span>DEFENSE FABRICATOR <small>SELECT A DEFENSE → CLICK A PAD</small></span><div>${button('cancel','CANCEL','text-button')}${button('speed','1×','speed-button','title="Simulation speed"')}${button('next','SEND HORDE <kbd>SPACE</kbd>','primary compact','id="next-wave"')}</div></div><div class="tower-dock">${TOWERS.map((t,i)=>`<button class="tower-card" data-action="tower:${i}" title="${t.desc}" style="--weapon:${t.color}"><kbd>${i+1}</kbd><img src="./assets/generated/turrets/weapons/${t.weapon}.png" alt=""><div><h3>${t.name}</h3><span>${t.role}</span></div><strong>${t.cost} <small>◇</small></strong></button>`).join('')}</div>`}<footer class="battle-footer"><span id="hint">${convoy?'WASD / ARROWS · DRIVE &nbsp; E · DEPLOY':'1–5 · BUILD &nbsp; CLICK TURRET · UPGRADE &nbsp; Q / R · SUPPORT'}</span><span id="run-clock"></span><span>ROADWATCH <i class="live-dot"></i> 87.9 FM</span></footer></section>`;updateHud();}
function updateHud(){if(screen!=='game')return;$('#hull-value').textContent=`${Math.ceil(game.hp)} / ${game.maxHp}`;$('#hull-fill').style.width=game.hp/game.maxHp*100+'%';$('#hull-fill').style.background=game.hp/game.maxHp<.3?'#e88a73':'';$('#scrap-value').textContent=game.scrap;$('#wave-value').innerHTML=`${String(game.wave).padStart(2,'0')}<small> / 09</small>`;let convoy=game.phase==='convoy',wave=game.phase==='wave';$('#phase-label').textContent=convoy?'SCAVENGE & POSITION':wave?'HORDE INBOUND':'BREATHING ROOM';$('#mission-title').textContent=targeting?'Mark the strike zone.':convoy?'A little further.':wave?(game.wave%3===0?'Something big is coming.':'Hold the line.'):'Make every turret count.';$('#mission-desc').textContent=targeting?'Click the battlefield to strike. Esc to cancel.':convoy?`${game.loot.length} salvage caches nearby. Deploy when you’re ready.`:wave?`${SECTORS[game.sector].risk}. Protect the command core.`:game.towers.length===0?'Select Watchman below, then click a + pad.':'Build, upgrade, or repair. Send the next horde when ready.';$('#hostiles').textContent=wave?`${game.enemies.length} HOSTILES · ${game.spawnLeft} APPROACHING`:convoy?'PROTECTED WHILE MOVING':`NEXT: WAVE ${game.wave+1}${(game.wave+1)%3===0?' · BRUTE INBOUND':''}`;$('#wave-progress').hidden=!wave;$('#wave-fill').style.width=(1-game.spawnLeft/(16+game.wave*8))*100+'%';$('#run-clock').textContent=`${String(Math.floor(game.time/60)).padStart(2,'0')}:${String(Math.floor(game.time%60)).padStart(2,'0')} · ${game.kills} ELIMINATED`;for(let name of ['strike','pulse']){$('#'+name+'-cd').textContent=game.cooldowns[name]>0?Math.ceil(game.cooldowns[name])+'s':(name==='strike'?'Q':'R')+' · READY';let b=$(`[data-action="${name}"]`);b.disabled=!wave||game.cooldowns[name]>0;b.classList.toggle('active',name==='strike'&&targeting);}$('[data-action="repair"]').disabled=convoy||game.scrap<65||game.hp>=game.maxHp;if($('#next-wave')){$('#next-wave').disabled=wave;$('#next-wave').innerHTML=wave?'HORDE ACTIVE <span class="live-dot"></span>':'SEND HORDE <kbd>SPACE</kbd>';TOWERS.forEach((t,i)=>{let card=$(`[data-action="tower:${i}"]`);card.classList.toggle('active',selection===i);card.classList.toggle('unaffordable',game.scrap<t.cost);card.setAttribute('aria-pressed',selection===i);});}if(selectedTower!==null)inspector();}
function inspector(){let p=$('#inspector'),t=game.towers.find(t=>t.id===selectedTower);if(!p)return;if(!t){p.hidden=true;return;}p.hidden=false;let d=TOWERS[t.type];p.innerHTML=`<div class="eyebrow">DEFENSE / LEVEL ${t.level}</div><h3>${d.name} <span>${'▰'.repeat(t.level)}</span></h3><p>${d.desc}</p><div class="inspect-stats"><span>${Math.round(d.damage*game.damageMult*(1+(t.level-1)*.65))}<small>DAMAGE</small></span><span>${Math.round(d.range*game.rangeMult*(1+(t.level-1)*.09))}<small>RANGE</small></span><span>${t.kills}<small>KILLS</small></span></div>${t.level<3?button('upgrade',`UPGRADE · ${game.upgradeCost(t)} ◇`,'primary compact',game.scrap<game.upgradeCost(t)?'disabled':''):'<div class="max-level">MAXIMUM LEVEL</div>'}${button('sell',`SALVAGE · +${Math.floor(t.spent*.7)} ◇`,'text-button')}${button('cancel','×','close-inspector','aria-label="Close tower details"')}`;}
function reward(){screen='reward';selection=null;selectedTower=null;targeting=false;let offers=[0,1,2].map(i=>BOONS[(game.wave*2+i*3+(i===2?1:0))%BOONS.length]); // distinct, deterministic choices
 offers=[...new Map(offers.map(b=>[b.id,b])).values()];for(let b of BOONS)if(offers.length<3&&!offers.includes(b))offers.push(b);
 modal(`WAVE ${String(game.wave).padStart(2,'0')} CLEARED // FIELD UPGRADE`,game.wave%3===0?'The road is opening.':'A little more dangerous.',`<p class="muted">Choose one permanent upgrade for this expedition.${game.wave%3===0?' Your defenses travel with you to the next sector.':''}</p><div class="boons">${offers.map(b=>`<button data-action="boon:${b.id}" class="boon"><span class="boon-icon">${b.icon}</span><small>${b.tag}</small><h3>${b.name}</h3><p>${b.desc}</p><strong>INSTALL UPGRADE ↗</strong></button>`).join('')}</div><div class="reward-note">+${90+game.wave*15} SCRAP SECURED <span>+50 HULL RESTORED</span></div>`,'','reward-modal');$('.modal-header > button').remove();}
function end(){screen='end';storage.remove('save');let best=Number(storage.get('best',0));storage.set('best',Math.max(best,game.score));modal(game.phase==='won'?'TRANSMISSION RESTORED // EXPEDITION COMPLETE':'SIGNAL LOST // EXPEDITION ENDED',game.phase==='won'?'Someone heard us.':'The road remembers.',`<p class="muted">${game.phase==='won'?'The relay is alive. Across three lost sectors, survivors are finding their way home. You held the line.':'The convoy fell, but every mile meant something. Rebuild your strategy and take the road again.'}</p><div class="end-stats"><div><strong>${game.score.toLocaleString()}</strong><span>EXPEDITION SCORE</span></div><div><strong>${game.wave}/9</strong><span>WAVES REACHED</span></div><div><strong>${game.kills}</strong><span>ELIMINATED</span></div></div><p class="small muted">${game.score>best?'NEW PERSONAL BEST · ':''}Saved on this device.</p>`,button('restart','ANOTHER EXPEDITION ↗','primary')+button('menu','RETURN TO TITLE','secondary'));}
let previous='menu';
function pause(){previous=screen;screen='pause';modal('ROADWATCH // SIGNAL HELD','Take a breath.',`<p class="muted">The road can wait. Your expedition is paused.</p><div class="pause-actions">${button('resume','RESUME EXPEDITION →','primary')}${button('settings','SETTINGS','secondary')}${button('help','FIELD MANUAL','secondary')}${button('map','EXPEDITION MAP','secondary')}${button('menu','RETURN TO TITLE','text-button')}</div><p class="small muted">Checkpoint: before the current wave. Returning to the title during a wave resumes from that checkpoint.</p>`);}
function settings(){let from=screen;if(from!=='settings')previous=from;screen='settings';modal('PREFERENCES // THIS DEVICE','Make yourself at home.',`<div class="settings-row"><div><h3>Sound effects</h3><p>Synthesized weapons, salvage, and support cues.</p></div>${button('sound',audioOn?'ON':'OFF','toggle',`aria-pressed="${audioOn}"`)}</div><div class="settings-row"><div><h3>Reduced motion</h3><p>Disable screen shake, pulsing, and interface animation.</p></div>${button('motion',reduced?'ON':'OFF','toggle',`aria-pressed="${reduced}"`)}</div><p class="small muted">Progress and preferences are stored locally on this browser.</p>`,button('back','DONE','primary'));}
function help(){if(screen!=='help')previous=screen;screen='help';modal('ROADWATCH // FIELD MANUAL','Drive. Deploy. Survive.',`<div class="manual"><article><b>01</b><div><h3>Make the most of the quiet.</h3><p>Drive into salvage crates for extra scrap. Move within the marked staging area, then deploy. Your location decides the final approach to your core.</p></div></article><article><b>02</b><div><h3>Build a defense that works together.</h3><p>Select a defense, then an empty + pad. Watchmen handle stragglers. Breakers punish groups. Arc coils slow them down. Cinders melt armor. Longshots hunt brutes. Click a turret to upgrade or salvage it.</p></div></article><article><b>03</b><div><h3>Stay in the fight.</h3><p>Send each wave when ready. Call airstrikes on dense groups and EMP enemies near your core. Every third wave brings a boss. Choose a permanent upgrade after each wave. All nine waves restore the relay.</p></div></article></div><div class="key-grid"><span><kbd>WASD / ↑↓←→</kbd> Drive</span><span><kbd>E</kbd> Deploy</span><span><kbd>1–5</kbd> Select defense</span><span><kbd>SPACE</kbd> Send horde</span><span><kbd>Q + CLICK</kbd> Airstrike</span><span><kbd>R</kbd> EMP pulse</span><span><kbd>WHEEL</kbd> Zoom</span><span><kbd>ESC</kbd> Cancel / pause</span></div><p class="small muted">Touch: use the arrow controls to drive and tap pads to build. Mouse: drag empty terrain to pan; F resets the view.</p><details><summary>Credits & original game</summary><p>Based on Deadroad.io’s mobile command and roadside defense concept, with its original generated vehicle, turret, and zombie assets. New expedition design, interface, terrain, and synthesized sound. <a href="./LICENSES.md">Asset credits</a> · <a href="./legacy.html?offline=1">Copied original sandbox</a>.</p></details>`,button('back','UNDERSTOOD','primary'));}
function map(){previous=screen;screen='map';modal('EXPEDITION ROUTE // 03 SECTORS','A signal worth following.',`<div class="route-map">${SECTORS.map((s,i)=>`<article class="route-stop ${i===game.sector?'current':''}"><div class="route-number">${i<game.sector?'✓':'0'+(i+1)}</div><small>${s.region}</small><h3>${s.name}</h3><p>${s.subtitle}</p><strong>${i<game.sector?'RECLAIMED':i===game.sector?'CURRENT SECTOR':'AHEAD'} · WAVES ${i*3+1}–${i*3+3}</strong></article>`).join('')}</div><p class="small muted">Clear three waves to move on. Your turrets, upgrades, and remaining scrap travel with the convoy.</p>`,button('back','BACK TO THE ROAD →','primary'));}
function back(){if(screen==='reward')return;if(screen==='setup'||screen==='end')return showMenu();if(screen==='pause')return renderHud();let dest=previous;previous='game';if(dest==='menu')showMenu();else if(dest==='setup')setup();else if(dest==='pause')pause();else renderHud();}
function act(action){let [a,v]=action.split(':');if(a==='sound'){audioOn=!audioOn;storage.set('sound',audioOn?'on':'off');if(screen==='menu')showMenu();else if(screen==='settings')settings();return;}if(a==='motion'){reduced=!reduced;renderer.reduced=reduced;document.body.classList.toggle('reduced',reduced);storage.set('motion',reduced?'off':'on');settings();return;}if(a==='begin'||a==='restart')return setup();if(a==='rig'){rig=v;return setup();}if(a==='difficulty'){difficulty=v;return setup();}if(a==='launch')return start();if(a==='continue')return start(true);if(a==='back')return back();if(a==='menu')return showMenu();if(a==='pause')return pause();if(a==='resume')return renderHud();if(a==='settings')return settings();if(a==='help')return help();if(a==='map')return map();if(a==='boon'){if(game.chooseBoon(v)){checkpoint();renderHud();if(game.phase==='convoy')toast('Sector reclaimed. Your turrets are packed. Find your next position.');}return;}
 if(screen!=='game')return;
 if(a==='deploy'&&game.deploy()){selection=0;renderHud();checkpoint();toast('Select a defense, then click a + pad. Your first Watchman costs 70 scrap.');}
 if(a==='tower'){selection=+v;selectedTower=null;targeting=false;$('#inspector').hidden=true;toast(TOWERS[selection].name+': '+TOWERS[selection].desc);}
 if(a==='cancel'){selection=null;selectedTower=null;targeting=false;$('#inspector').hidden=true;}
 if(a==='next'){if(!game.towers.length){toast('Build at least one defense before sending the horde.');return;}checkpoint();if(game.startWave()){selection=null;selectedTower=null;$('#inspector').hidden=true;}}
 if(a==='upgrade'&&game.upgrade(selectedTower))checkpoint();if(a==='sell'){game.sell(selectedTower);selectedTower=null;$('#inspector').hidden=true;checkpoint();}if(a==='repair'){if(game.repair()){checkpoint();toast('Field repair complete. +250 hull.');}}
 if(a==='strike'&&game.phase==='wave'&&game.cooldowns.strike<=0){targeting=!targeting;selection=null;selectedTower=null;$('#inspector').hidden=true;}
 if(a==='pulse')game.pulse();if(a==='speed'){speed=speed===1?2:1;$('[data-action="speed"]').textContent=speed+'×';}
 if(a==='zoom-in')renderer.zoom=clamp(renderer.zoom+.15,.7,1.8);if(a==='zoom-out')renderer.zoom=clamp(renderer.zoom-.15,.7,1.8);if(a==='focus'){renderer.zoom=1;renderer.offset={x:0,y:0};}updateHud();}
app.addEventListener('click',e=>{let b=e.target.closest('[data-action]');if(b&&!b.disabled)act(b.dataset.action);});
app.addEventListener('pointerdown',e=>{let b=e.target.closest('[data-action^="drive:"]');if(b){e.preventDefault();let d=b.dataset.action.split(':')[1];touchVector={x:d==='left'?-1:d==='right'?1:0,y:d==='up'?-1:d==='down'?1:0};b.setPointerCapture(e.pointerId);}});
window.addEventListener('pointerup',()=>touchVector={x:0,y:0});window.addEventListener('pointercancel',()=>{touchVector={x:0,y:0};drag=null;});
const canvas=$('#field');canvas.addEventListener('pointerdown',e=>{if(screen!=='game')return;canvas.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};renderer.pointer=renderer.world(e.clientX,e.clientY);});
canvas.addEventListener('pointermove',e=>{renderer.pointer=renderer.world(e.clientX,e.clientY);if(drag&&!targeting){if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>7)drag.moved=true;if(drag.moved){renderer.offset.x=clamp(renderer.offset.x+e.clientX-drag.lastX,-500,500);renderer.offset.y=clamp(renderer.offset.y+e.clientY-drag.lastY,-300,300);}drag.lastX=e.clientX;drag.lastY=e.clientY;}});
canvas.addEventListener('pointerup',e=>{if(screen!=='game'||!drag){drag=null;return;}let moved=drag.moved;drag=null;if(moved)return;let p=renderer.world(e.clientX,e.clientY);if(targeting){if(game.strike(p.x,p.y))targeting=false;updateHud();return;}if(game.phase==='convoy')return;let t=game.towers.find(t=>dist(t,p)<35);if(t){selectedTower=t.id;selection=null;inspector();return;}let pad=game.pads.findIndex(t=>dist(t,p)<36);if(pad>=0&&selection!==null){if(game.build(selection,pad)){checkpoint();updateHud();}else toast(game.scrap<TOWERS[selection].cost?'Not enough scrap for that defense.':'That pad is occupied.');}else{selectedTower=null;$('#inspector').hidden=true;}});
canvas.addEventListener('wheel',e=>{if(screen!=='game')return;e.preventDefault();renderer.zoom=clamp(renderer.zoom-e.deltaY*.001,.7,1.8);},{passive:false});canvas.addEventListener('contextmenu',e=>{e.preventDefault();if(screen==='game')act('cancel');});
window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;const key=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();keys.add(key);if(e.repeat)return;if(key==='escape'){if(screen==='game'){if(selection!==null||selectedTower!==null||targeting)act('cancel');else pause();}else back();return;}if(screen!=='game')return;if(/^[1-5]$/.test(key)&&game.phase!=='convoy')act('tower:'+(Number(key)-1));else if(key==='e')act('deploy');else if(key===' ')act('next');else if(key==='q')act('strike');else if(key==='r')act('pulse');else if(key==='m')act('map');else if(key==='f')act('focus');});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
window.addEventListener('blur',()=>{keys.clear();touchVector={x:0,y:0};drag=null;if(screen==='game')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&screen==='game'){keys.clear();pause();}});
function frame(now){let dt=Math.min((now-last)/1000,.05);last=now;if(screen==='game'){
 let input={x:(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0)+touchVector.x,y:(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0)+touchVector.y};
 let remaining=dt*speed;while(remaining>0){let step=Math.min(remaining,1/60);game.update(step,input);remaining-=step;}
 for(const event of game.events.splice(0)){sound(event.type);if(event.type==='salvage')toast('Salvage secured. Keep moving, or deploy with E.');if(event.type==='boss')toast('HEAVY CONTACT. A brute is approaching. Save your airstrike.');if(event.type==='clear')reward();if(event.type==='won'||event.type==='lost')end();}
 hudClock+=dt;if(hudClock>.12){updateHud();hudClock=0;}}
 renderer.draw(game,{selection,selectedTower,targeting,menu:screen==='menu'||screen==='setup'});requestAnimationFrame(frame);}
showMenu();requestAnimationFrame(frame);
