import {WORLD,SECTORS,TOWERS,seeded,dist} from './engine.js';
export class Renderer{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.images={};this.zoom=1;this.offset={x:0,y:0};this.pointer={x:-999,y:-999};this.reduced=false;this.background=null;this.sector=-1;this.load();this.resize();window.addEventListener('resize',()=>this.resize());}
 load(){const paths={core:'base/base_mobile_command_core.png',truck:'base/base_mobile_command_core_packed.png',damaged:'base/base_mobile_command_core_damaged.png',shambler:'zombies/zombie_shambler.png',runner:'zombies/zombie_runner.png',bloater:'zombies/zombie_bloater.png',armored:'zombies/zombie_armored.png',boss:'zombies/zombie_brute.png',chassis:'turrets/chassis/fortified_base.png'};TOWERS.forEach(t=>paths[t.id]='turrets/weapons/'+t.weapon+'.png');for(const [name,path]of Object.entries(paths)){let im=new Image();im.src='./assets/generated/'+path;this.images[name]=im;}}
 resize(){this.dpr=Math.min(devicePixelRatio||1,2);this.w=innerWidth;this.h=innerHeight;this.canvas.width=this.w*this.dpr;this.canvas.height=this.h*this.dpr;this.canvas.style.width=this.w+'px';this.canvas.style.height=this.h+'px';}
 camera(){const mobile=this.w<760;let usable=this.h-(mobile?270:180);this.scale=Math.min(this.w/WORLD.w,usable/850)*this.zoom;this.ox=this.w/2-800*this.scale+this.offset.x;this.oy=(mobile?105:78)+(usable-850*this.scale)/2-80*this.scale+this.offset.y;}
 world(x,y){return {x:(x-this.ox)/this.scale,y:(y-this.oy)/this.scale};}
 sprite(name,x,y,size,angle=0){let im=this.images[name];if(!im?.complete||!im.naturalWidth)return false;const c=this.ctx;c.save();c.translate(x,y);c.rotate(angle);const ratio=im.naturalHeight/im.naturalWidth;c.drawImage(im,-size/2,-size*ratio/2,size,size*ratio);c.restore();return true;}
 makeBackground(sector){this.sector=sector;let canvas=document.createElement('canvas');canvas.width=WORLD.w;canvas.height=WORLD.h;let c=canvas.getContext('2d'),s=SECTORS[sector],rng=seeded(731+sector*79);c.fillStyle=s.ground;c.fillRect(0,0,WORLD.w,WORLD.h);for(let i=0;i<17000;i++){let x=rng()*WORLD.w,y=rng()*WORLD.h;c.fillStyle=rng()>.5?'#bec0930c':'#050e1420';c.fillRect(x,y,rng()*4+1,rng()*3+1);}
  const road=(lane,width,color)=>{c.beginPath();lane.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.strokeStyle=color;c.lineWidth=width;c.lineJoin='round';c.stroke();};
  if(sector===1){c.beginPath();c.moveTo(0,70);c.bezierCurveTo(500,120,550,320,950,220);c.bezierCurveTo(1200,120,1250,220,1600,100);c.lineWidth=95;c.strokeStyle='#18343c';c.stroke();c.lineWidth=1;c.strokeStyle='#80b2b533';c.stroke();}
  for(const lane of s.lanes){road(lane,87,'#16201db0');road(lane,72,'#737166');road(lane,62,'#303735');road(lane,52,'#363d3a');c.setLineDash([16,20]);road(lane,2,'#c4ba7975');c.setLineDash([]);}
  // The convoy road is deliberately quiet: the final dashed connection shows the base's chosen location.
  c.fillStyle='#978a6b10';c.fillRect(210,555,1180,320);
  function distanceToRoad(x,y){let best=9999;for(const lane of s.lanes)for(let i=1;i<lane.length;i++){let [ax,ay]=lane[i-1],[bx,by]=lane[i],dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,((x-ax)*dx+(y-ay)*dy)/(dx*dx+dy*dy)));best=Math.min(best,Math.hypot(x-ax-t*dx,y-ay-t*dy));}return best;}
  for(let i=0;i<440;i++){let x=rng()*1600,y=rng()*1050;if((y>490&&y<910&&x>165&&x<1420)||distanceToRoad(x,y)<70)continue;let r=10+rng()*25;c.fillStyle='#091b2055';c.beginPath();c.ellipse(x+9,y+12,r,r*.6,0,0,7);c.fill();if(sector===2&&rng()>.4){c.strokeStyle='#262a23';c.lineWidth=4;c.beginPath();c.moveTo(x,y+15);c.lineTo(x,y-r);c.lineTo(x-10,y-r-7);c.moveTo(x,y-r/2);c.lineTo(x+12,y-r);c.stroke();}else{for(let j=0;j<3;j++){c.fillStyle=['#142c27','#284438',s.color][j];c.beginPath();c.moveTo(x,y-r+j*9);c.lineTo(x-r*(1-j*.16),y+r*.6+j*5);c.lineTo(x+r*(1-j*.16),y+r*.6+j*5);c.closePath();c.fill();}}}
  for(let i=0;i<22;i++){let x=rng()*1600,y=rng()*470;if(distanceToRoad(x,y)<90)continue;c.save();c.translate(x,y);c.rotate((rng()-.5)*.2);c.fillStyle='#111e1b88';c.fillRect(-30,-15,70,50);c.fillStyle=sector===2?'#655a48':'#4c5548';c.fillRect(-34,-24,62,38);c.strokeStyle='#93907c55';c.strokeRect(-34,-24,62,38);c.fillStyle='#28332f';c.fillRect(-30,-20,54,5);c.restore();}
  c.font='600 13px monospace';c.fillStyle='#b5c2ae40';c.fillText('ROADWATCH // '+s.region,60,970);c.fillText('SECTOR 0'+(sector+1)+'    GRID 38.6 N / 90.2 W',1160,970);this.background=canvas;
 }
 draw(g,{selection=null,selectedTower=null,targeting=false,menu=false}={}){
  this.camera();let c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.fillStyle='#101b1a';c.fillRect(0,0,this.w,this.h);if(this.sector!==g.sector)this.makeBackground(g.sector);c.save();let shake=this.reduced?0:g.shake*7;c.translate(this.ox+(Math.random()-.5)*shake,this.oy+(Math.random()-.5)*shake);c.scale(this.scale,this.scale);c.drawImage(this.background,0,0);
  const time=performance.now()/1000;
  if(g.phase!=='convoy'){
   for(const route of g.routes){let from=route[route.length-2];c.setLineDash([7,10]);c.lineWidth=2;c.strokeStyle='#d5bd7560';c.beginPath();c.moveTo(from.x,from.y);c.lineTo(g.core.x,g.core.y);c.stroke();c.setLineDash([]);}
   for(const route of g.routes){let p=route[0],next=route[1],x=p.x===0?60:p.x===1600?1540:p.x,y=p.y===0?55:p.y;c.save();c.translate(x,y);c.rotate(Math.atan2(next.y-p.y,next.x-p.x));c.fillStyle='#df816dcc';c.beginPath();c.moveTo(12,0);c.lineTo(-7,-8);c.lineTo(-7,8);c.fill();c.restore();}
   let tower=g.towers.find(t=>t.id===selectedTower);if(tower||selection!==null){let point=tower||g.pads.find(p=>dist(p,this.pointer)<45);if(point){let type=tower?tower.type:selection,range=TOWERS[type].range*g.rangeMult*(1+((tower?.level||1)-1)*.09);c.fillStyle=TOWERS[type].color+'0b';c.strokeStyle=TOWERS[type].color+'65';c.lineWidth=1.5;c.beginPath();c.arc(point.x,point.y,range,0,Math.PI*2);c.fill();c.setLineDash([5,7]);c.stroke();c.setLineDash([]);}}
   g.pads.forEach((p,i)=>{if(g.towers.some(t=>t.pad===i))return;let hover=dist(p,this.pointer)<40;c.fillStyle=hover?'#c7d6b333':'#131f1d88';c.strokeStyle=selection!==null?'#e7bf81aa':'#8cac8155';c.lineWidth=1.5;c.beginPath();c.roundRect(p.x-22,p.y-22,44,44,8);c.fill();c.stroke();c.font='18px monospace';c.textAlign='center';c.fillStyle=selection!==null?'#e5c995':'#a3b39d75';c.fillText('+',p.x,p.y+6);});
  }else{
   c.setLineDash([8,12]);c.strokeStyle='#bdd28c33';c.lineWidth=2;c.strokeRect(220,560,1160,290);c.setLineDash([]);
   for(const l of g.loot){c.save();c.translate(l.x,l.y);c.strokeStyle='#dfc181';c.fillStyle='#4c4d32';c.lineWidth=2;c.fillRect(-15,-12,30,24);c.strokeRect(-15,-12,30,24);c.beginPath();c.moveTo(-15,-12);c.lineTo(15,12);c.moveTo(15,-12);c.lineTo(-15,12);c.stroke();c.fillStyle='#e4cf9e';c.font='11px monospace';c.textAlign='center';c.fillText('+'+l.value,0,-25-Math.sin(time*2)*3);c.restore();}
  }
  for(const fx of g.effects.filter(e=>e.type==='death')){c.globalAlpha=fx.t/fx.max*.45;c.fillStyle='#7b5645';c.beginPath();c.ellipse(fx.x,fx.y,15,8,0,0,7);c.fill();c.globalAlpha=1;}
  let objects=[...g.towers.map(t=>({...t,kind:'tower'})),...g.enemies.map(e=>({...e,kind:'enemy'})),{...g.core,kind:'core'}].sort((a,b)=>a.y-b.y);
  for(const o of objects){c.fillStyle='#06141160';c.beginPath();c.ellipse(o.x+5,o.y+8,o.kind==='core'?48:o.kind==='tower'?24:12,9,0,0,7);c.fill();if(o.kind==='core'){
    if(g.phase!=='convoy'){let pulse=this.reduced?0:Math.sin(time*2)*.08;c.strokeStyle=`rgba(167,206,162,${.15+pulse})`;c.lineWidth=1;c.beginPath();c.arc(o.x,o.y,65,0,7);c.stroke();}
    this.sprite(g.phase==='convoy'?'truck':g.hp/g.maxHp<.35?'damaged':'core',o.x,o.y,125,g.phase==='convoy'?o.a:0);c.fillStyle='#101a17';c.fillRect(o.x-36,o.y+45,72,4);c.fillStyle=g.hp/g.maxHp<.3?'#df826b':'#a8c99a';c.fillRect(o.x-36,o.y+45,72*g.hp/g.maxHp,4);c.textAlign='center';c.font='bold 10px monospace';c.fillStyle='#d8e2c7';c.fillText(g.phase==='convoy'?'YOUR CONVOY':'COMMAND CORE',o.x,o.y+65);
   }else if(o.kind==='tower'){const def=TOWERS[o.type];if(o.id===selectedTower){c.strokeStyle=def.color;c.lineWidth=2;c.beginPath();c.arc(o.x,o.y,34,0,7);c.stroke();}this.sprite('chassis',o.x,o.y,56);this.sprite(def.id,o.x,o.y,55,o.a+Math.PI/2);c.fillStyle=def.color;for(let j=0;j<o.level;j++)c.fillRect(o.x-7+j*7,o.y+27,4,3);
   }else{let size=o.type==='boss'?70:o.type==='bloater'?41:o.type==='armored'?38:29;let wobble=this.reduced?0:Math.sin(time*8+o.wobble)*1.5;this.sprite(o.type,o.x+Math.cos(o.a+1.57)*o.offset*.3,o.y+wobble,size,o.a+Math.PI/2);if(o.slow>0){c.strokeStyle='#83d7e0aa';c.beginPath();c.arc(o.x,o.y,size*.44,0,7);c.stroke();}if(o.hp<o.maxHp||o.type==='boss'){c.fillStyle='#101917';c.fillRect(o.x-size/2,o.y-size*.7,size,3);c.fillStyle=o.type==='boss'?'#ef9278':'#b8bb86';c.fillRect(o.x-size/2,o.y-size*.7,size*o.hp/o.maxHp,3);}}
  }
  for(const fx of g.effects){let progress=1-fx.t/fx.max;c.globalAlpha=Math.min(1,fx.t/fx.max*2);if(fx.type==='beam'){c.strokeStyle=fx.color;c.lineWidth=2;c.beginPath();c.moveTo(fx.x,fx.y);c.lineTo(fx.tx,fx.ty);c.stroke();c.fillStyle='#fff0bc';c.beginPath();c.arc(fx.tx,fx.ty,3,0,7);c.fill();}else if(fx.type==='shell'){c.strokeStyle='#f3b57e';c.lineWidth=3;c.beginPath();c.arc(fx.tx,fx.ty,80*progress,0,7);c.stroke();}else if(fx.type==='flame'){let grad=c.createLinearGradient(fx.x,fx.y,fx.tx,fx.ty);grad.addColorStop(0,'#ffe5a9');grad.addColorStop(1,'#e87b3633');c.strokeStyle=grad;c.lineWidth=14;c.beginPath();c.moveTo(fx.x,fx.y);c.lineTo(fx.tx,fx.ty);c.stroke();}else if(fx.type==='strike'||fx.type==='pulse'){let radius=(fx.type==='strike'?175:340)*progress;c.strokeStyle=fx.type==='strike'?'#efb17a':'#8fd4d1';c.fillStyle=fx.type==='strike'?'#f0ad6333':'#83d3d011';c.lineWidth=4*(1-progress);c.beginPath();c.arc(fx.x,fx.y,radius,0,7);c.fill();c.stroke();}c.globalAlpha=1;}
  if(targeting){c.strokeStyle='#eaa47c';c.fillStyle='#eaa47c15';c.lineWidth=2;c.beginPath();c.arc(this.pointer.x,this.pointer.y,175,0,7);c.fill();c.stroke();c.beginPath();c.moveTo(this.pointer.x-18,this.pointer.y);c.lineTo(this.pointer.x+18,this.pointer.y);c.moveTo(this.pointer.x,this.pointer.y-18);c.lineTo(this.pointer.x,this.pointer.y+18);c.stroke();}
  c.restore();if(!menu){const grad=c.createRadialGradient(this.w*.5,this.h*.45,this.h*.18,this.w*.5,this.h*.45,this.w*.65);grad.addColorStop(0,'#00000000');grad.addColorStop(1,'#06131380');c.fillStyle=grad;c.fillRect(0,0,this.w,this.h);}
 }
}
