const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const out = require('node:path').join(require('node:os').tmpdir(), 'grid-io-3d-qa');
require('node:fs').mkdirSync(out, { recursive: true });
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const errors = [], failed = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
    page.on('pageerror', e => errors.push(e.message));
    page.on('response', r => { if (r.status() >= 400 && !r.url().endsWith('chase-cover.png')) failed.push(r.status() + ' ' + r.url()); });
    await page.goto((process.env.GRID3D_BASE_URL || 'http://127.0.0.1:5276') + '/grid-io-3d/?test=1');
    await page.waitForFunction(() => !document.getElementById('play').disabled);
    await page.locator('#play').click();
    await page.waitForFunction(() => window.__GRID_TEST__.state === 'playing');
    await page.evaluate(() => { const p = window.__GRID_TEST__.arena.player; p.grace = 500; p.length = p.peak = 300; });
    assert.equal(await page.evaluate(() => window.__GRID_TEST__.graphics.camera.type), 'PerspectiveCamera');
    let heading = await page.evaluate(() => window.__GRID_TEST__.arena.player.angle);
    await page.keyboard.down('KeyD');
    await page.waitForTimeout(350);
    await page.keyboard.up('KeyD');
    assert(await page.evaluate(h => window.__GRID_TEST__.arena.player.angle > h + 0.1, heading));
    await page.keyboard.down('Shift');
    await page.waitForFunction(() => window.__GRID_TEST__.snapshot().boost);
    await page.keyboard.up('Shift');
    await page.keyboard.press('Space');
    await page.waitForFunction(() => window.__GRID_TEST__.snapshot().height > 3);
    await page.screenshot({ path: out + '/jump.png' });
    await page.keyboard.down('KeyC');
    await page.waitForFunction(() => window.__GRID_TEST__.graphics.lookBack);
    await page.keyboard.up('KeyC');
    await page.waitForFunction(() => !window.__GRID_TEST__.graphics.lookBack);
    await page.keyboard.press('Escape');
    const paused = await page.evaluate(() => window.__GRID_TEST__.arena.time);
    await page.waitForTimeout(200);
    assert.equal(await page.evaluate(() => window.__GRID_TEST__.arena.time), paused);
    await page.locator('#quality').click();
    await page.locator('#resume').click();
    await page.waitForTimeout(150);
    await page.screenshot({ path: out + '/gameplay.png' });
    await page.keyboard.press('Escape');
    await page.locator('#quit').click();
    await page.locator('#garage').click();
    await page.getByRole('button', { name: 'Bulwark', exact: true }).click();
    await page.getByRole('button', { name: 'Tread', exact: true }).click();
    await page.getByRole('button', { name: 'Female', exact: true }).click();
    await page.screenshot({ path: out + '/garage.png' });
    await page.locator('#garage-dialog .close-action').click();
    await page.locator('[data-mode="90"]').click();
    await page.locator('#play').click();
    await page.evaluate(() => { window.__GRID_TEST__.arena.player.grace = 500; });
    heading = await page.evaluate(() => window.__GRID_TEST__.arena.player.angle);
    await page.keyboard.press('KeyD');
    await page.waitForFunction(h => window.__GRID_TEST__.arena.player.angle !== h, heading);
    assert.equal(await page.evaluate(() => window.__GRID_TEST__.arena.player.angle), heading + Math.PI / 2);
    await page.keyboard.press('KeyD');
    await page.waitForFunction(h => window.__GRID_TEST__.arena.player.angle === h + Math.PI, heading);
    await page.keyboard.press('KeyA');
    await page.waitForFunction(h => window.__GRID_TEST__.arena.player.angle === h + Math.PI / 2, heading);
    assert.equal(await page.evaluate(() => window.__GRID_TEST__.graphics.getBike(window.__GRID_TEST__.arena.player).group.getObjectByName('rear-drive-assembly') !== undefined), true);
    await page.evaluate(() => { const a = window.__GRID_TEST__.arena; Object.assign(a.player, { x: 1199.9, angle: 0, grace: 0 }); });
    await page.waitForFunction(() => window.__GRID_TEST__.state === 'dead');
    await page.locator('#retry').click();
    await page.waitForFunction(() => window.__GRID_TEST__.state === 'playing');
    await page.keyboard.press('Escape');
    await page.locator('#quit').click();
    await page.reload();
    await page.waitForFunction(() => !document.getElementById('play').disabled);
    assert.equal(await page.evaluate(() => window.__GRID_TEST__.loadout.body), 'bulwark');
    await page.reload(); await page.waitForTimeout(4300);
    await page.screenshot({ path: out + '/menu.png' });
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
    mobile.on('pageerror', e => errors.push(e.message));
    await mobile.goto((process.env.GRID3D_BASE_URL || 'http://127.0.0.1:5276') + '/grid-io-3d/?test=1');
    await mobile.waitForFunction(() => !document.getElementById('play').disabled);
    await mobile.waitForTimeout(4300); await mobile.screenshot({ path: out + '/mobile-menu.png' });
    await mobile.locator('#play').tap();
    await mobile.evaluate(() => { window.__GRID_TEST__.arena.player.grace = 500; });
    assert(await mobile.locator('#joystick').isVisible());
    await mobile.locator('#jump-button').tap();
    await mobile.waitForFunction(() => window.__GRID_TEST__.snapshot().cooldown > 0);
    await mobile.screenshot({ path: out + '/mobile-game.png' });
    assert.equal(await mobile.evaluate(() => document.documentElement.scrollWidth), 390);
    assert.deepEqual(errors, []); assert.deepEqual(failed, []);
    console.log('PASS desktop/mobile, perspective camera, steering, boost, jump, rear view, pause, quality, garage persistence, 90-degree turns, crash and retry; no script or asset errors.');
    console.log(await mobile.evaluate(() => window.__GRID_TEST__.snapshot()));
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
