import {grantMissionGold} from './economy';
const key='jump-daily-v1';
const day=()=>new Date().toISOString().slice(0,10);
type Daily={day:string;height:number;top10:number;rounds:number;seen:string[];claimed:string[]};
function load():Daily{try{const d=JSON.parse(localStorage.getItem(key)||'null');if(d?.day===day())return d;}catch{}return {day:day(),height:0,top10:0,rounds:0,seen:[],claimed:[]};}
export function missionProgress(round:string,height:number,place?:number){const d=load();if(place===undefined&&Math.floor(height/10)<=d.height)return;d.height=Math.max(d.height,Math.floor(height/10));if(place!==undefined&&!d.seen.includes(round)){d.seen.push(round);d.rounds++;if(place<=10)d.top10++;}localStorage.setItem(key,JSON.stringify(d));}
export function createMissions(root:HTMLElement,onReward:()=>void){
 const toggle=document.createElement('button');toggle.type='button';toggle.className='missions-toggle';toggle.setAttribute('aria-label','Daily missions');toggle.setAttribute('aria-haspopup','dialog');toggle.innerHTML='<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M8 6H4v23h24V6h-4M11 3h10v6H11zM10 15l2 2 4-4M19 16h4M10 23l2 2 4-4M19 24h4"/></svg><span>Missions</span><b class="mission-badge" hidden></b>';
 const dialog=document.createElement('dialog');dialog.className='social-dialog missions-dialog';dialog.setAttribute('aria-label','Daily missions');dialog.innerHTML='<header><div><p class="social-eyebrow">A LITTLE HIGHER, EVERY DAY</p><h2>Daily missions</h2></div><button type="button" aria-label="Close daily missions">×</button></header>';
 const box=document.createElement('section');box.className='daily-missions';box.setAttribute('aria-label','Mission progress');dialog.append(box);root.append(toggle,dialog);
 dialog.querySelector('header button')!.addEventListener('click',()=>dialog.close());dialog.addEventListener('keydown',e=>e.stopPropagation());dialog.addEventListener('keyup',e=>e.stopPropagation());
 toggle.onclick=()=>{render();dialog.showModal();};
 const tasks=[{id:'height',label:'Climb 100m',target:100,gold:2},{id:'top10',label:'Finish top 10 twice',target:2,gold:4},{id:'rounds',label:'Finish 3 rounds',target:3,gold:3}] as const;
 const render=()=>{const d=load();box.innerHTML='<p class="mission-reset">New missions at 00:00 UTC · Complete a climb to count finishing missions.</p>';let available=0;for(const t of tasks){const row=document.createElement('div'),label=document.createElement('div'),claim=document.createElement('button');row.className='mission-row';label.innerHTML=`<strong>${t.label}</strong><small>${Math.min(d[t.id],t.target)} / ${t.target}</small><progress value="${Math.min(d[t.id],t.target)}" max="${t.target}" aria-label="${t.label}"></progress>`;claim.type='button';claim.textContent=d.claimed.includes(t.id)?'Claimed':`+${t.gold} gold`;claim.disabled=d.claimed.includes(t.id)||d[t.id]<t.target;if(!claim.disabled)available++;claim.onclick=()=>{const now=load();if(now[t.id]<t.target||now.claimed.includes(t.id))return;if(grantMissionGold(now.day+':'+t.id,t.gold)){now.claimed.push(t.id);localStorage.setItem(key,JSON.stringify(now));onReward();render();}};row.append(label,claim);box.append(row);}const badge=toggle.querySelector<HTMLElement>('.mission-badge')!;badge.hidden=available===0;badge.textContent=String(available);};
 render();const timer=setInterval(render,30000);return ()=>{clearInterval(timer);dialog.remove();toggle.remove();};
}
