import assert from 'node:assert/strict';
import { loadCampaign, saveCampaign, createCharacter, activeCharacter, settleCharacter, buyUpgrade, CAMPAIGN_KEY } from '../client/src/game/Campaign';
import { LocalSimulation } from '../client/src/net/LocalSimulation';
import { TOWER_INFO } from '../client/src/game/constants';
const storage=new Map<string,string>();
const store={getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)};
Object.assign(globalThis,{localStorage:store,sessionStorage:store,window:{setInterval:()=>1,setTimeout:()=>1,clearInterval:()=>{},clearTimeout:()=>{},addEventListener:()=>{},removeEventListener:()=>{},dispatchEvent:()=>true}});
let c=loadCampaign(); assert.equal(c.slots.length,3); const ch=createCharacter(c,'Rook');
settleCharacter(c,ch.id,200,650,true); assert.deepEqual(c.bank,{xp:100,scrap:100});
settleCharacter(c,ch.id,200,650,true); assert.deepEqual(c.bank,{xp:100,scrap:100},'death must never pay twice');
assert.equal(activeCharacter(loadCampaign())?.status,'dead');
createCharacter(c,'Successor'); assert.equal(c.history.length,1); assert(buyUpgrade(c,'armor')); assert.equal(c.upgrades.armor,1);
c.selected=1; const second=createCharacter(c,'Mara'); assert.equal(c.slots[0]?.name,'Successor'); assert.equal(c.slots[1]?.name,'Mara');
settleCharacter(c,second.id,0,250,true); assert.equal(c.bank.scrap,0,'starting resources cannot be farmed');
c.selected=0; c.upgrades.turrets=2; c.upgrades.field=2; saveCampaign(c);
const notices:string[]=[]; const sim=new LocalSimulation('Successor',()=>{},n=>notices.push(n.text));const state=sim as any;
assert.equal(state.player.equipmentStash[0].count,2);
const lot=state.lots.find((l:any)=>l.status==='empty');sim.deploy(lot.id);const base=state.bases[0];assert.equal(base.maxHp,1150);
base.coreX=lot.x;base.coreY=lot.y;base.lastMovedAt=0;sim.deployConvoy();assert.equal(base.status,'setup',notices.join('\n'));
sim.build(lot.pads[0].id,'rifle');assert.equal(state.towers[0].damage,TOWER_INFO.rifle.damage*1.2);
state.player.scrap=800;state.player.xp=300;base.hp=777;
const contract=state.contracts[0];contract.queue=['shambler'];
assert.equal(sim.extractToHideout(),false,'extraction cannot skip queued horde');
sim.saveCharacter();const saved=loadCampaign();const serialized=storage.get(CAMPAIGN_KEY)!;console.log('Campaign save bytes:',serialized.length);assert(serialized.length<3_000_000);
assert.equal(saved.slots[0]?.run.bases[0].hp,777);assert.equal(saved.slots[0]?.run.contracts[0].queue.length,1);
sim.dispose();const resumed=new LocalSimulation('Successor',()=>{},()=>{});const resumedState=resumed as any;
assert.equal(resumedState.bases[0].hp,777);assert.equal(resumedState.player.scrap,800);assert.equal(resumedState.towers.length,1);assert.equal(resumedState.contracts[0].queue.length,1);
resumedState.contracts[0].queue=[];resumedState.player.turretRewards=[{type:'rifle',path:'damage',tier:1}];assert(resumed.extractToHideout());c=loadCampaign();assert.equal(c.bank.xp,325);assert.equal(c.bank.scrap,550);
assert.equal(c.stash.length,1,'extracted hardware belongs to the shared Hideout');
c.selected=2;createCharacter(c,'Scout');assert.equal(loadCampaign().stash.length,1,'new characters share recovered loot');c.selected=0;saveCampaign(c);
assert(resumed.extractToHideout());assert.deepEqual(loadCampaign().bank,c.bank,'repeat extraction cannot duplicate rewards');
assert.equal(loadCampaign().stash.length,1,'repeat extraction cannot duplicate hardware');
resumedState.player.xp=500;resumedState.player.scrap=650;resumedState.loseCharacter();c=loadCampaign();assert.equal(c.slots[0]?.status,'dead');assert.deepEqual(c.bank,{xp:425,scrap:650});
resumed.saveCharacter();assert.equal(loadCampaign().slots[0]?.run,undefined,'dead save must not be resurrected');
resumed.dispose();
console.log('PASS: 3-slot isolation, successor memorial, death idempotency, reward farming protection, real armor/turret/field bonuses, save/restore with active horde, extraction checks and rewards, permanent death.');
