import assert from 'node:assert/strict';
import {loadCampaign,saveCampaign,createCharacter} from '../client/src/game/Campaign';
import {hideout,purchase,convoyStats} from '../client/src/game/Hideout';
import {LocalSimulation} from '../client/src/net/LocalSimulation';
import {TOWER_INFO} from '../client/src/game/constants';
const data=new Map<string,string>();const storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>data.set(k,v)};
Object.assign(globalThis,{localStorage:storage,sessionStorage:storage,window:{setInterval:()=>1,setTimeout:()=>1,clearInterval:()=>{},clearTimeout:()=>{},addEventListener:()=>{},removeEventListener:()=>{},dispatchEvent:()=>true}});
let c=loadCampaign();createCharacter(c,'Tester');c.bank={xp:20,scrap:5000};saveCampaign(c);
assert(purchase('turret','rifle'));assert(purchase('convoy','bastion','health'));assert(purchase('convoy','bastion','speed'));assert(purchase('convoy','bastion','capacity'));assert(purchase('supply','airstrike'));
c=loadCampaign();assert.equal(c.bank.xp,20);assert.equal(c.bank.scrap,4395);hideout(c).convoy='bastion';saveCampaign(c);assert.equal(convoyStats().hull,1350);assert.equal(convoyStats().capacity,8);
assert(!purchase('convoy','locked','health'));assert(!purchase('supply','fake'));
let sim=new LocalSimulation('Tester',()=>{},()=>{});let s=sim as any;assert.equal(s.player.equipmentStash.find((i:any)=>i.type==='airstrike').count,1);assert.deepEqual(hideout(loadCampaign()).supplies,{});sim.saveCharacter();sim.dispose();
sim=new LocalSimulation('Tester',()=>{},()=>{});s=sim as any;assert.equal(s.player.equipmentStash.find((i:any)=>i.type==='airstrike').count,1,'reload must not duplicate supplies');
sim.deploy(s.lots.find((l:any)=>l.status==='empty').id);const base=s.bases[0];assert.equal(base.maxHp,1350);base.lastMovedAt=0;sim.deployConvoy(true);const contract=s.contracts[0];s.player.scrap=10000;
sim.build(contract.buildPads[0].id,'rifle');assert.equal(s.towers[0].damage,TOWER_INFO.rifle.damage*1.15);
const point={x:base.coreX+100,y:base.coreY};s.zombies=[{id:'target',type:'shambler',contractId:contract.id,territoryId:base.territoryId,...point,hp:700,maxHp:700,alive:true,routePoints:[]}];
sim.useEquipment('airstrike',point);assert.equal(s.zombies[0].hp,100);assert.equal(s.player.equipmentStash.find((i:any)=>i.type==='airstrike'),undefined);sim.useEquipment('airstrike',point);assert.equal(s.zombies[0].hp,100,'empty airstrike cannot deal damage');
const random=Math.random;Math.random=()=>0;for(let i=0;i<100;i++)s.rollLootDrop(s.zombies[0]);Math.random=random;assert(s.lootSatchels.every((b:any)=>b.itemType!=='airstrike'));
sim.dispose();c=loadCampaign();assert.equal(hideout(c).turrets.rifle,1);c.bank.scrap=0;saveCampaign(c);assert(!purchase('supply','airstrike'));assert(!purchase('turret','rifle'));
console.log('PASS: scrap-only purchases, permanent bonuses, convoy hull/capacity, supply transfer/reload, airstrike damage/consumption, loot exclusion, insufficient funds.');
