import { planetOneWorldRoads } from "../game/roadEditor/PlanetOneRoadNetwork";
import type { RoadsideLot, WorldStatic } from "../game/types";
import { normalGameplayHighways } from "../game/HighwayOnlyRoadPolicy";
import type { BiomeType, DeploymentLot, GlobeWorld, Settlement, SettlementKind, TerrainType, WorldRegion, WorldRiver, WorldRoad, WorldTile } from "./GlobeData";
import { addAuthoredRoadCorridors, buildRoadNetwork, connectRoadNetworks, printRoadQualityReport, refreshRoadQualityReports, roadDistanceDegrees, type ContinentRoadConfig, type GeoPoint } from "./RoadSystem";
import { isEarthLandAt } from "./EarthTextureGenerator";
import { earthTerritoryAt, earthTerritoryRegions, nearestOverrunRegion, overrunEarthRegions } from "./EarthTerritories";
import { US_INTERSTATE_CORRIDORS, US_ROAD_HUBS } from "./USRoadNetwork";

const ROWS = 24; const COLS = 36;

export const earthRegions: WorldRegion[] = [...earthTerritoryRegions, ...overrunEarthRegions];

const earthRoadContinents: ContinentRoadConfig[] = [
  { id: "north-america", label: "North and Central American", bounds: { latMin: 7, latMax: 72, lonMin: -168, lonMax: -52 }, gridStep: 1.5, coverageStep: 3, status: "clear", major: true, serviceNodeCount: 0, roadGeneration: "authored", contains: (point) => { const group = earthTerritoryAt(point.lat, point.lon)?.group ?? ""; return ["usa", "canada", "mexico", "central-america"].includes(group) && !(group === "canada" && point.lat > 64); } },
  { id: "south-america", label: "South American", bounds: { latMin: -56, latMax: 13, lonMin: -83, lonMax: -34 }, gridStep: 2.5, coverageStep: 3, status: "contested", major: true, serviceNodeCount: 0, roadGeneration: "highway_only", contains: (point) => earthTerritoryAt(point.lat, point.lon)?.group === "south-america" }
];

type HubSeed = [id: string, name: string, kind: SettlementKind, continentId: string, lat: number, lon: number, importance: number];
const hubSeeds: HubSeed[] = [
  ["labrador", "Labrador Roadwatch", "military_checkpoint", "north-america", 50, -57, 56],
  ["anchorage", "Anchorage Haven", "survivor_city", "north-america", 61, -149, 78], ["yellowknife", "Yellowknife Relay", "radio_tower", "north-america", 62, -114, 58], ["seattle", "Seattle Haven", "survivor_city", "north-america", 47, -122, 90], ["los-angeles", "Los Angeles Ruins", "ruined_city", "north-america", 34, -118, 83], ["denver", "Denver Citadel", "capital_hub", "north-america", 39, -105, 82], ["dallas", "Dallas Exchange", "trader_town", "north-america", 33, -97, 80], ["chicago", "Chicago Junction", "bridge_town", "north-america", 42, -88, 86], ["atlanta", "Atlanta Watch", "military_checkpoint", "north-america", 34, -84, 76], ["new-york", "Atlantic Ruins", "ruined_city", "north-america", 41, -74, 92], ["mexico-city", "Mexico Relay", "survivor_city", "north-america", 20, -99, 82], ["baja", "Baja Roadwatch", "military_checkpoint", "north-america", 28, -113, 56], ["minneapolis", "Northstar Post", "trader_town", "north-america", 46, -93, 58], ["new-orleans", "Delta Bridge", "bridge_town", "north-america", 30, -90, 60], ["miami", "Miami Quarantine", "hospital_ruin", "north-america", 26, -80, 46], ["halifax", "Halifax Coastwatch", "trader_town", "north-america", 45, -63, 58], ["guatemala", "Guatemala Checkpoint", "military_checkpoint", "north-america", 15, -90, 43], ["san-jose", "San Jose Roadwatch", "survivor_hub", "north-america", 10, -84, 54], ["panama", "Panama Crossing", "bridge_town", "north-america", 9, -79.5, 68],
  ["bogota", "Bogota Haven", "survivor_city", "south-america", 5, -74, 85], ["lima", "Lima Outpost", "port", "south-america", -12, -77, 82], ["manaus", "Amazon Crossing", "bridge_town", "south-america", -3, -60, 75], ["brasilia", "Brasilia Citadel", "capital_hub", "south-america", -16, -48, 76], ["sao-paulo", "Sao Paulo Ruins", "ruined_city", "south-america", -23, -47, 88], ["buenos-aires", "Buenos Haven", "survivor_city", "south-america", -35, -59, 86], ["santiago", "Andes Gate", "military_checkpoint", "south-america", -33, -71, 80], ["caracas", "Caracas Exchange", "trader_town", "south-america", 10, -67, 72], ["quito", "Quito Pass", "military_checkpoint", "south-america", 0, -78, 55], ["recife", "Recife Port", "port", "south-america", -8, -35, 48], ["brazil-coast", "Brazil Coast Watch", "military_checkpoint", "south-america", -20, -42, 50], ["patagonia", "Patagonia Relay", "radio_tower", "south-america", -45, -68, 42], ["fireland", "Fireland Checkpoint", "military_checkpoint", "south-america", -52, -70, 48], ["asuncion", "Asuncion Nest", "infestation_nest", "south-america", -25, -57, 32],
  ["lisbon", "Lisbon Harbor", "port", "europe", 39, -9, 75], ["madrid", "Madrid Haven", "survivor_city", "europe", 40, -4, 82], ["paris", "Paris Citadel", "capital_hub", "europe", 49, 2, 90], ["berlin", "Berlin Checkpoint", "military_checkpoint", "europe", 52, 13, 88], ["rome", "Rome Exchange", "trader_town", "europe", 42, 12, 82], ["warsaw", "Warsaw Junction", "bridge_town", "europe", 52, 21, 78], ["kyiv", "Kyiv Ruins", "ruined_city", "europe", 50, 30, 78], ["baltic-haven", "Baltic Haven", "survivor_city", "europe", 54, 18, 74], ["channel", "Channel Citadel", "fortress", "europe", 50, 2, 64], ["vienna", "Vienna Relay", "radio_tower", "europe", 48, 16, 55], ["athens", "Athens Port", "port", "europe", 38, 23, 48], ["eastern-gate", "Eastern Gate", "military_checkpoint", "europe", 48, 28, 50], ["baltic-hospital", "Baltic Hospital", "hospital_ruin", "europe", 54, 20, 30],
  ["cairo", "Cairo Necropolis", "ruined_city", "africa", 30, 31, 90], ["casablanca", "Casablanca Harbor", "port", "africa", 34, -7, 75], ["dakar", "Dakar Watch", "military_checkpoint", "africa", 15, -17, 72], ["lagos", "Lagos Exchange", "trader_town", "africa", 7, 4, 85], ["addis", "Addis Citadel", "capital_hub", "africa", 9, 39, 74], ["nairobi", "Nairobi Haven", "survivor_city", "africa", -1, 37, 78], ["kinshasa", "Congo Crossing", "bridge_town", "africa", -4, 15, 76], ["johannesburg", "Johannesburg Fort", "fortress", "africa", -26, 28, 82], ["tunis", "Tunis Relay", "radio_tower", "africa", 37, 10, 52], ["bamako", "Bamako Checkpoint", "military_checkpoint", "africa", 13, -8, 48], ["somalia", "Somalia Coast Watch", "military_checkpoint", "africa", 10, 49, 46], ["khartoum", "Nile Nest", "infestation_nest", "africa", 16, 33, 32], ["cape-town", "Cape Town Port", "port", "africa", -34, 18, 55],
  ["moscow", "Moscow Exclusion", "ruined_city", "asia", 56, 38, 92], ["istanbul", "Istanbul Crossing", "bridge_town", "asia", 41, 29, 78], ["tehran", "Tehran Citadel", "capital_hub", "asia", 36, 51, 82], ["delhi", "Delhi Ruins", "ruined_city", "asia", 29, 77, 90], ["mumbai", "Mumbai Harbor", "port", "asia", 19, 73, 86], ["novosibirsk", "Siberia Haven", "survivor_city", "asia", 55, 83, 75], ["bangkok", "Bangkok Crossing", "bridge_town", "asia", 14, 100, 76], ["beijing", "Beijing Maw", "infestation_nest", "asia", 40, 116, 92], ["seoul", "Seoul Checkpoint", "military_checkpoint", "asia", 37, 127, 80], ["wuhan", "Wuhan Signal", "radio_tower", "asia", 30, 114, 88], ["kunming", "Kunming Exchange", "trader_town", "asia", 25, 102, 74], ["hanoi-factory", "Hanoi Industrial Ruins", "industrial_ruin", "asia", 22, 105, 72], ["guangdong", "Guangdong Watch", "military_checkpoint", "asia", 23, 114, 52], ["riyadh", "Riyadh Outpost", "trader_outpost", "asia", 25, 47, 52], ["karachi", "Karachi Port", "port", "asia", 25, 67, 58], ["hanoi", "Hanoi Relay", "radio_tower", "asia", 21, 106, 55], ["irkutsk", "Irkutsk Factory", "industrial_ruin", "asia", 52, 104, 30], ["far-east", "Far East Watch", "military_checkpoint", "asia", 55, 135, 50],
  ["perth", "Perth Haven", "survivor_city", "australia", -32, 116, 82], ["darwin", "Darwin Watch", "military_checkpoint", "australia", -12, 131, 74], ["adelaide", "Adelaide Exchange", "trader_town", "australia", -35, 139, 76], ["melbourne", "Melbourne Citadel", "capital_hub", "australia", -38, 145, 84], ["sydney", "Sydney Fortress", "fortress", "australia", -34, 151, 90], ["brisbane", "Brisbane Port", "port", "australia", -27, 153, 78], ["alice-springs", "Outback Relay", "radio_tower", "australia", -24, 134, 52], ["cairns", "Cairns Hospital", "hospital_ruin", "australia", -17, 146, 30], ["victoria", "Victoria Outpost", "trader_outpost", "australia", -36, 145, 45],
  ["antarctic-west", "West Ice Station", "survivor_hub", "antarctica", -75, -150, 76], ["antarctic-zero", "Prime Meridian Station", "military_checkpoint", "antarctica", -75, 0, 74], ["antarctic-east", "East Ice Relay", "radio_tower", "antarctica", -75, 90, 72], ["antarctic-peninsula", "Peninsula Watch", "military_checkpoint", "antarctica", -72, -66, 52], ["antarctic-peninsula-west", "Peninsula West Watch", "radio_tower", "antarctica", -72, -102, 50], ["antarctic-ninety", "Ninety West Relay", "radio_tower", "antarctica", -76, -90, 50], ["antarctic-forty", "Forty East Watch", "military_checkpoint", "antarctica", -76, 45, 48], ["antarctic-far-east", "Far East Station", "trader_outpost", "antarctica", -76, 145, 46], ["antarctic-inner-west", "Inner West Survey", "radio_tower", "antarctica", -82, -140, 52], ["antarctic-inner-west-two", "Inner West Two", "military_checkpoint", "antarctica", -82, -80, 50], ["antarctic-inner-zero", "Inner Meridian Survey", "military_checkpoint", "antarctica", -82, -20, 50], ["antarctic-inner-east", "Inner East Survey", "trader_outpost", "antarctica", -82, 40, 48], ["antarctic-inner-east-two", "Inner East Two", "radio_tower", "antarctica", -82, 100, 48], ["antarctic-inner-far-east", "Inner Far East", "trader_outpost", "antarctica", -82, 145, 46], ["antarctic-maw", "Buried Ice Maw", "infestation_nest", "antarctica", -78, 35, 28]
];

function snapToEarthLand(point: GeoPoint): GeoPoint { if (isEarthLandAt(point.lat, point.lon)) return point; for (let radius = .5; radius <= 7; radius += .5) for (let index = 0; index < 24; index++) { const angle = index / 24 * Math.PI * 2; const candidate = { lat: point.lat + Math.sin(angle) * radius, lon: point.lon + Math.cos(angle) * radius / Math.max(.3, Math.cos(point.lat * Math.PI / 180)) }; if (isEarthLandAt(candidate.lat, candidate.lon)) return candidate; } return point; }
const regionById = (id: string) => earthRegions.find((region) => region.id === id)!;
const regionForPoint = (point: GeoPoint) => { const territory = earthTerritoryAt(point.lat, point.lon); return territory ? regionById(territory.id) : nearestOverrunRegion(point.lat, point.lon); };
const nearCoast = (point: GeoPoint) => [[2, 0], [-2, 0], [0, 2], [0, -2]].some(([lat, lon]) => !isEarthLandAt(point.lat + lat, point.lon + lon));

function biomeFor(lat: number, lon: number, elevation: number, rain: number): BiomeType {
  if (Math.abs(lat) > 67) return "mountains"; if ((lat > 13 && lat < 33 && lon > -17 && lon < 56) || (lat < -18 && lon > 112 && lon < 145)) return "wasteland";
  if ((lon > -82 && lon < -48 && lat > -20 && lat < 9) || (lon > 12 && lon < 31 && lat > -8 && lat < 8) || (lon > 95 && lon < 125 && lat > -8 && lat < 20)) return "dead_forest";
  if (elevation > .72) return "mountains"; if (rain > .67) return "swamp"; if (Math.abs(lat) < 48 && rain > .35) return "prairie"; return "wasteland";
}

const terrainAt = (point: GeoPoint) => { const elevation = Math.max(0, Math.min(1, .47 + Math.sin(point.lon * .08) * .2 + Math.cos(point.lat * .12) * .18)); const rainfall = Math.max(0, Math.min(1, .48 + Math.sin(point.lon * .04 - point.lat * .09) * .3)); const region = earthTerritoryAt(point.lat, point.lon); return { elevation, slope: Math.abs(Math.sin(point.lon * .13 + point.lat * .17)) * .45, threat: region?.threat ?? 5, biome: biomeFor(point.lat, point.lon, elevation, rainfall), rainfall }; };

const activeHubSeeds: HubSeed[] = [...new Map([...hubSeeds, ...US_ROAD_HUBS.map((hub): HubSeed => [hub.id, hub.name, hub.kind, "north-america", hub.lat, hub.lon, hub.importance])].map((seed) => [seed[0], seed])).values()];
export const earthSettlements: Settlement[] = activeHubSeeds.flatMap(([id, name, kind, continentId, sourceLat, sourceLon, importance]) => { if (!["north-america", "south-america"].includes(continentId)) return []; const point = snapToEarthLand({ lat: sourceLat, lon: sourceLon }); const terrain = terrainAt(point); const territory = earthTerritoryAt(point.lat, point.lon); if (!territory) return []; return [{ id: `earth-${id}`, name, kind, ...point, threat: territory.threat, regionId: territory.id, continentId, importance, nearRiver: ["bridge_town", "hospital_ruin"].includes(kind), nearCoast: nearCoast(point), elevation: terrain.elevation }]; });

const routingRivers: WorldRiver[] = [
  { id: "earth-mississippi", name: "Mississippi", size: "large_river", pointLatLon: [{ lat: 47, lon: -95 }, { lat: 40, lon: -91 }, { lat: 34, lon: -91 }, { lat: 29, lon: -90 }] },
  { id: "earth-amazon", name: "Amazon", size: "large_river", pointLatLon: [{ lat: -4, lon: -73 }, { lat: -3, lon: -64 }, { lat: -3, lon: -54 }, { lat: -1, lon: -49 }] }
];

const hostileKinds: SettlementKind[] = ["ruined_city", "industrial_ruin", "hospital_ruin", "factory_ruin", "infestation_nest"];
const deploymentAnchorIds = [
  "earth-dallas", "earth-los-angeles", "earth-denver", "earth-atlanta", "earth-new-orleans", "earth-miami", "earth-seattle", "earth-chicago", "earth-kansas-city", "earth-st-louis", "earth-phoenix", "earth-austin", "earth-wichita", "earth-albuquerque"
] as const;

export function closestHighwayAccess(roads: readonly WorldRoad[], anchor: GeoPoint, continentId: string): { road: WorldRoad; point: GeoPoint; route: GeoPoint[] } {
  const candidates = normalGameplayHighways(roads).filter((road) => road.continentId === continentId && road.pointLatLon.length >= 2); let best: { road: WorldRoad; point: GeoPoint; segment: number; distance: number } | undefined; const lonScale = Math.max(.25, Math.cos(anchor.lat * Math.PI / 180));
  for (const road of candidates) for (let segment = 1; segment < road.pointLatLon.length; segment++) {
    const a = road.pointLatLon[segment - 1]; const b = road.pointLatLon[segment]; const ax = (a.lon - anchor.lon) * lonScale; const ay = a.lat - anchor.lat; const bx = (b.lon - anchor.lon) * lonScale; const by = b.lat - anchor.lat; const dx = bx - ax; const dy = by - ay; const lengthSquared = dx * dx + dy * dy; const t = lengthSquared ? Math.max(0, Math.min(1, -(ax * dx + ay * dy) / lengthSquared)) : 0; const point = { lat: a.lat + (b.lat - a.lat) * t, lon: a.lon + (b.lon - a.lon) * t }; const distance = roadDistanceDegrees(anchor, point);
    if (!best || distance < best.distance) best = { road, point, segment, distance };
  }
  if (!best) throw new Error(`No highway is available near ${anchor.lat},${anchor.lon}`);
  const a = best.road.pointLatLon[best.segment - 1]; const b = best.road.pointLatLon[best.segment]; const approach = roadDistanceDegrees(a, best.point) > roadDistanceDegrees(b, best.point) ? b : a;
  return { road: best.road, point: best.point, route: [approach, best.point] };
}

export function createNaturalEarthGlobeWorld(warWorld: GlobeWorld): GlobeWorld {
  return { tiles: warWorld.tiles.map((tile) => ({ ...tile, hasRoad: false, hasRiver: false, hasSettlement: false, roadIds: [], riverIds: [], settlementIds: [] })), regions: warWorld.regions, roads: [], rivers: [], settlements: [], lots: warWorld.lots.map((lot) => ({ ...lot, roadId: "", routePointLatLon: undefined })), roadNodes: [], roadStamps: [], roadValidationIssues: [], bridges: [], roadQualityReports: [] };
}

export function createEarthGlobeWorld(_world: WorldStatic, tacticalLots: RoadsideLot[]): GlobeWorld {
  const network = buildRoadNetwork({ continents: earthRoadContinents, settlements: earthSettlements, rivers: routingRivers, landAt: (point) => isEarthLandAt(point.lat, point.lon), terrainAt });
  addAuthoredRoadCorridors(network, US_INTERSTATE_CORRIDORS.map((corridor) => ({
    id: `usa-${corridor.id}`,
    name: corridor.name,
    continentId: "north-america",
    anchors: corridor.anchorIds.map((id) => {
      const hub = US_ROAD_HUBS.find((entry) => entry.id === id)!;
      return { id: hub.id, label: hub.name, lat: hub.lat, lon: hub.lon, settlementId: `earth-${hub.id}`, importance: hub.importance };
    })
  })));
  addAuthoredRoadCorridors(network, [{ id: "pan-american-north", name: "Pan-American Backbone", continentId: "north-america", anchors: ["mexico-city", "guatemala", "san-jose", "panama"].map((id) => { const settlement = earthSettlements.find((entry) => entry.id === `earth-${id}`)!; return { id, label: settlement.name, lat: settlement.lat, lon: settlement.lon, settlementId: settlement.id, importance: settlement.importance ?? 80 }; }) }]);
  connectRoadNetworks(network, { fromSettlementId: "earth-panama", toSettlementId: "earth-bogota", renderClass: "highway", bridgeSegmentIndex: 2, waypoints: [{ lat: 8.5, lon: -80 }, { lat: 8.5, lon: -78 }, { lat: 7.4, lon: -77 }, { lat: 6.1, lon: -75.8 }] });
  const highwayRoads = [...normalGameplayHighways(network.roads).filter(road => !road.pointLatLon.some(p => p.lat >= 24 && p.lat <= 50 && p.lon >= -125 && p.lon <= -66)), ...planetOneWorldRoads()];
  const lotAccess = tacticalLots.map((lot, index) => { const anchorSettlementId = deploymentAnchorIds[index % deploymentAnchorIds.length]; const anchor = earthSettlements.find((entry) => entry.id === anchorSettlementId)!; const continentId = anchor.continentId!; const localHostiles = earthSettlements.filter((entry) => entry.continentId === continentId && hostileKinds.includes(entry.kind)); const origin = localHostiles[index % Math.max(1, localHostiles.length)] ?? anchor; const access = closestHighwayAccess(highwayRoads, anchor, continentId); network.totalDeploymentLots.set(continentId, (network.totalDeploymentLots.get(continentId) ?? 0) + 1); network.connectedDeploymentLots.set(continentId, (network.connectedDeploymentLots.get(continentId) ?? 0) + 1); return { lot, origin, access }; });
  refreshRoadQualityReports(network);
  printRoadQualityReport(network.reports, "Earth");
  const tiles: WorldTile[] = [];
  for (let row = 0; row < ROWS; row++) for (let col = 0; col < COLS; col++) { const centerLat = 90 - (row + .5) * 180 / ROWS; const centerLon = -180 + (col + .5) * 360 / COLS; const land = isEarthLandAt(centerLat, centerLon); const region = regionForPoint({ lat: centerLat, lon: centerLon }); const sample = terrainAt({ lat: centerLat, lon: centerLon }); const terrain: TerrainType = sample.biome === "mountains" ? "mountainous" : sample.biome === "swamp" ? "marsh" : sample.elevation > .62 ? "large_hills" : sample.elevation > .48 ? "small_hills" : "flat"; tiles.push({ id: `earth-tile-${row}-${col}`, centerLat, centerLon, biome: sample.biome, terrain, state: land ? region.state : "safe", elevation: sample.elevation, rainfall: sample.rainfall, temperature: Math.max(0, 1 - Math.abs(centerLat) / 90), threat: land ? region.threat : 0, infestation: land ? region.infestation : 0, hasRoad: false, hasRiver: false, hasSettlement: false, hasInfestation: false, hasDeployLot: false, roadIds: [], riverIds: [], settlementIds: [], deployLotIds: [], regionId: region.id, isLand: land, continentId: earthTerritoryAt(centerLat, centerLon)?.group }); }
  const landTiles = tiles.filter((tile) => tile.isLand); const nearestTile = (point: GeoPoint, candidates = tiles) => candidates.reduce((best, tile) => roadDistanceDegrees(point, { lat: tile.centerLat, lon: tile.centerLon }) < roadDistanceDegrees(point, { lat: best.centerLat, lon: best.centerLon }) ? tile : best);
  for (const road of highwayRoads) for (const point of road.pointLatLon) { const tile = nearestTile(point); tile.hasRoad = true; if (!tile.roadIds.includes(road.id)) tile.roadIds.push(road.id); }
  for (const settlement of earthSettlements) { const tile = nearestTile(settlement, landTiles); tile.hasSettlement = true; tile.settlementIds.push(settlement.id); tile.hasInfestation ||= hostileKinds.includes(settlement.kind); }
  const lots: DeploymentLot[] = lotAccess.map(({ lot, origin, access }, index) => { const tile = nearestTile(access.point, landTiles); const region = regionForPoint(access.point); const status: DeploymentLot["status"] = lot.status === "occupied" ? "occupied" : lot.status === "reserved" ? "reserved" : lot.status === "blocked" ? "blocked" : lot.status === "overrun" || region.state === "overrun" ? "overrun" : "available"; const result: DeploymentLot = { id: `earth-${lot.id}`, tacticalLotId: lot.id, tileId: tile.id, roadId: access.road.id, regionId: region.id, name: `${["Interchange", "Overpass", "Rest Area", "Toll Gate", "Roadwatch"][index % 5]} ${String(index + 1).padStart(2, "0")}`, status, safetyRating: Math.max(1, 6 - region.threat), routeDanger: region.threat + 1, setupTimeSeconds: 60, startingScrapBonus: tile.biome === "mountains" ? 55 : 35, ...access.point, infestationSourceId: origin.id, routePointLatLon: access.route }; tile.hasDeployLot = true; tile.deployLotIds.push(result.id); tile.hasRoad = true; if (!tile.roadIds.includes(access.road.id)) tile.roadIds.push(access.road.id); return result; });
  return { tiles, regions: earthRegions, roads: highwayRoads, rivers: [], settlements: earthSettlements, lots, roadNodes: network.nodes, roadExits: [], roadPois: [], roadStamps: [], roadValidationIssues: [], bridges: network.bridges, roadQualityReports: network.reports };
}

