import {icon} from './icons';
export function editorMarkup(): string {
  const tool=(id:string,name:string,glyph:string)=>'<button class="editor-tool" data-tool="'+id+'" aria-label="'+name+'" title="'+name+'">'+icon(glyph)+'<span>'+name+'</span></button>';
  const button=(id:string,name:string,glyph:string)=>'<button class="editor-square" data-action="'+id+'" aria-label="'+name+'" title="'+name+'">'+icon(glyph)+'</button>';
  return '<header class="editor-top"><div class="editor-brand"><img src="'+import.meta.env.BASE_URL+'assets/menu/forged-command/logo.png" alt="">WORKSHOP</div><div class="editor-palette" aria-label="Draggable textured parts"></div><div class="editor-top-actions">'+button('save','Save map','save')+button('menu','Map menu','menu')+'<button class="editor-square" data-action="help" aria-label="Help and controls" title="Help and controls">?</button></div></header>'+
  '<main class="editor-stage" aria-label="Map editing canvas"><button class="editor-map-card" data-action="maps" aria-label="Select map"><img alt="" draggable="false"><span></span></button><nav class="editor-left-tools" aria-label="Editor tools">'+tool('select','Select','select')+tool('pan','Pan','pan')+tool('erase','Eraser','erase')+tool('start','Start','flag')+'<button class="editor-tool" data-action="randomize" aria-label="Randomize" title="Randomize">'+icon('dice')+'<span>Randomize</span></button></nav>'+
  '<nav class="editor-right-tools" aria-label="Edit actions">'+button('undo','Undo','undo')+button('redo','Redo','redo')+'<div class="tool-separator"></div>'+button('home','Go to start','home')+button('overview','Map overview','focus')+button('view','View options','grid')+'</nav>'+
  '<div class="editor-selection" hidden><span class="editor-selection-count"></span><button data-action="testhere" aria-label="Test from selection" title="Test from selection">'+icon('play')+'</button><button data-action="duplicate" aria-label="Duplicate" title="Duplicate">'+icon('copy')+'</button><button data-action="properties" aria-label="Object properties" title="Object properties">'+icon('tune')+'</button><button data-action="delete" aria-label="Delete selection" title="Delete selection" class="editor-danger">'+icon('trash')+'</button></div></main>'+
  '<footer class="editor-bottom"><button data-action="test" class="editor-play" aria-label="Playtest">'+icon('play')+'<span>Play</span></button><div class="editor-title-area"><input class="editor-map-name" aria-label="Map name" maxlength="80"><span class="editor-save-state" role="status">Draft ready</span><span class="editor-course-state"></span></div>'+
  '<div class="editor-test-bar" hidden><button data-action="flight" aria-label="God flight" title="God flight">'+icon('fly')+'<span>Fly</span></button><button data-action="checkpoint" aria-label="Set retry point" title="Set retry point">'+icon('flag')+'<span>Set point</span></button><button data-action="retry" aria-label="Retry jump" title="Retry jump">'+icon('retry')+'<span>Retry</span></button></div>'+
  '<div class="editor-ai" aria-label="AI testers"><button data-action="airemove" aria-label="Remove AI tester">−</button><button class="editor-ai-person" aria-label="Drag AI tester" title="Drag AI tester">'+icon('person')+'<span class="editor-ai-count">0</span></button><button data-action="aiadd" aria-label="Add AI tester">+</button></div><div class="editor-zoom"><button data-action="zoomout" aria-label="Zoom out">−</button><span class="editor-zoom-value">100%</span><button data-action="zoomin" aria-label="Zoom in">+</button></div></footer><div class="editor-toast" role="status" hidden></div><input type="file" accept=".json,application/json" class="editor-file" hidden><dialog class="editor-dialog"></dialog>';
}
export const helpMarkup=()=>'<div class="editor-help-grid">'+
'<section><h4>Build</h4><p>Drag a textured piece from the tray into the map. Drag an object to move it; pull its square corner to resize. Drag the curved arrow beyond that corner to rotate; Shift snaps to 15°.</p><p><kbd>V</kbd> Select · <kbd>H</kbd> Pan · <kbd>E</kbd> Eraser · <kbd>S</kbd> Player start</p></section>'+
'<section><h4>Select & erase</h4><p>Drag a box around a group. Select moves the group; Eraser deletes enclosed objects when you release. Click an object to erase only that one.</p><p><kbd>Shift</kbd> adds to selection · <kbd>Delete</kbd> removes · <kbd>Ctrl Z</kbd> undoes.</p></section>'+
'<section><h4>Playtest</h4><p><kbd>A D</kbd> or arrows to walk. Hold <kbd>Space</kbd> to charge, then release to jump. <kbd>Tab</kbd> switches between editing and play.</p><p>Select a platform and press its Play button to begin there.</p></section>'+
'<section><h4>Fly & retry</h4><p><kbd>F</kbd> toggles invulnerable flight. Use <kbd>W A S D</kbd> or arrows; click to teleport while flying. F again restores gravity.</p><p><kbd>C</kbd> sets a retry point; <kbd>R</kbd> returns to it, including moving-platform timing.</p></section>'+
'<section><h4>Spawn & AI</h4><p>Start selects a platform and sets the middle of the shared spawn zone. Drag the start marker to move it. Players spread across supported spots on that platform.</p><p>The person button adds AI testers; + and − change their number. Drag the person into the world to start one there. They attempt normal jumps and retry after falling. Right-drag pans while you watch.</p></section><section><h4>Move around</h4><p>Right-drag pans; the wheel zooms. The overview jumps to another area. In playtest it teleports you in flight.</p><p><kbd>Ctrl D</kbd> duplicates · <kbd>Ctrl Shift Z</kbd> redoes · arrows nudge.</p></section>'+
'<section><h4>Keep your maps</h4><p><kbd>Ctrl S</kbd> saves to My maps. Your working draft also autosaves in this browser.</p><p>The menu exports and imports portable map files. Export a file to hand off for the main game. Nothing publishes automatically.</p></section>'+
'<section><h4>Randomize</h4><p>Set the theme, jump count, width, and difficulty. Every accepted course has a complete physics-tested route of ordinary jumps. Your edits can change its reachability.</p></section>'+
'<section><h4>View options</h4><p>Surfaces up to 45° from horizontal support standing; steeper surfaces slide downhill. Hold jump to crouch and grip any slope, then release to launch. Grid, collision outlines, snap size, and playtest hazards are optional. Background scenery belongs to its theme.</p></section></div>';
